# Generated by Django 2.0.7 on 2018-07-04 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microsoft_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='microsoftaccount',
            name='microsoft_id',
            field=models.CharField(max_length=36, verbose_name='microsoft account id'),
        ),
    ]
