language: python
python: '3.6'
install:
  - pip install .[dev]
script:
  - make check
  - tox
after_success:
  - coveralls
deploy:
  provider: pypi
  user: hbschr
  on:
    tags: true
  password:
    secure: omMVodLqBNHlsr9zvg67s2yUmVc5ZO8oshF3mACWELUq5pMaRV/BBeahVh/NB1Euvf+kNumHjrfw+WV8iGR3d36B3w14GC3WBll/6nJSKim/ScoGqEvVSjltEJmqgehVcrzEXWcxjZHYGJnVXWqkPPa9GVJZP+yLRXRs4g5gH1Fo1h+WAYpVDGrJM3cGy9snrUhVzzLHE8gRVgO9BVUH+iJnZTz5eptYTFGpQet7Sv/A+2g7yUjTwOMC13gvJgBFdaKXeeSHOxcQTESI18RMpmrN+mqwRJVcMCRYeqwoYXxZUlrQYtQW2LVpd8jQ2HUXRsFaw4T1wtfIN8feOjbzhowf+NMzy+TZuPavvCdHEu9vEXclE7V97hNqPnU6UgVggfZ+IiSKG9GMk8epPOFfXPKevpZ4pnny2u/IyHZiOQmwkLHpmSOPSH6f9ZjuaTJZyqcCF36H3zTg5pzz3EQehe5y/E9jIGSGbO6xJvYtGuhsPqmrtUovXvZrQ4xLG/vRgOXMxFAMhXZ13FDNU3TinccKcgmebZVteEe9KaSOSdvh60VKnYNl02MtgC8cSDICISPqUj7zayoAGFPcIDoWsGVQDhm3xuvgAzmdWNgS2FyocEKGb8sClOIrMtm8MkmFaA4RBTBu82m7eTWIbGeArYLUO4LpZymASnJC02fNR9g=
