# Generated by Django 2.0.6 on 2018-06-25 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raceratings', '0007_auto_20180625_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='racebadge',
            name='badge_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='badges', to='raceratings.BadgeType'),
        ),
    ]
