# Generated by Django 2.0.6 on 2018-06-27 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raceratings', '0010_auto_20180627_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='racerating',
            name='rating_date',
        ),
    ]
