# Generated by Django 2.0.6 on 2018-06-11 16:13

import account.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuperAccount',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('display_name', models.CharField(default='', max_length=256, verbose_name='昵称')),
                ('valid', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'super_account',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', account.models.AccountManager()),
            ],
        ),
    ]
