
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-06-26T00:14:16+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "f9d444b90fead4343149d79f6892375f3ba4ce6f",
 "version": "0.99.10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
