# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-06-11 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_review_display_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='highlight',
            field=models.BooleanField(default=False),
        ),
    ]
