# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-06-20 09:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0011_auto_20180611_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='highlight',
        ),
    ]
