#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['nolimit', 'nolimit.nolimit_sympy']

package_data = \
{'': ['*']}

install_requires = \
['PyQt5', 'matplotlib', 'sympy', 'numpy']

entry_points = \
{'console_scripts': ['nolimit = nolimit:main.main',
                     'nolimit_sympy = '
                     'nolimit:nolimit_sympy.nolimit_sympy.main']}

setup(name='nolimit',
      version='1.0',
      description='is a Qt5 gui to solve limits, it has two commands:',
      author=' Simone Massaro (mone27), Saverio Morelli (Sav22999) ',
      author_email='mone.massaro@gmail.com, saverio.morelli@outlook.it',
      url='https://github.com/Sav22999/project_nolimit_math',
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      entry_points=entry_points,
     )
