## Holds all of the server parameters
##
## Note:
##    The folder structure for flask can get complicated. See the variables below for their
##    purposes. One can generally set staticFolder without staticURLPath, but not the reverse.
##    For more information of flask folder structure,
##    see (for example): https://stackoverflow.com/a/18746493
##
## Author: Raymond Ehlers <raymond.ehlers@cern.ch>, Yale University

#: Sets the ip address.
ipAddress: "127.0.0.1"

#: Sets the port.
port: 8850

#: Setup Bcrypt.
bcryptLogRounds: &bcryptLogRounds 12

#: Default user name. An empty string will disable it.
#: Should only be used when behind CERN SSO!
defaultUsername: ""

#: basePath is just a useful value.
#: It defines a base directory to reference if the static, template, etc folders are
#: all in the same dir.
basePath: ""

#: staticFolder is the disk location of the static folder.
#: It is a flask defined variable.
#: To check if the static files are from the front-end webserver, use:
#: https://stackoverflow.com/questions/16595691/static-files-with-flask-in-production
#:
#: (ie. add + "CHANGE" to the staticFolder location specified here).
#staticFolder = os.path.join(sharedParameters.staticFolderName) 
staticFolder: *staticFolder

#: staticURLPath is the URL of the static folder.
#: If you want to access "foo", it would be at $BASE_URL/staticURLPath/foo. "" is just the root.
#: It is a flask defined variable.
staticURLPath: "/static"

#: protectedFolder is the disk location of the protected folder.
#: This folder holds the experimental data.
protectedFolder: *dataFolder

#: docsFolder is the disk location of the docs folder.
docsFolder: &docsFolder "doc"

#: docsBuildFolder is the disk location of the docs html folder.
docsBuildFolder: !joinPaths
    - *docsFolder
    - "build"
    - "html"

#: Subsystems which have templates available (determined on startup).
#: Since this is run from the root directory, we need to go into the "webApp" directory to find the templates!
availableRunPageTemplates: !findRunPageTemplates
    - ".."
    - "webApp"
    - *templateFolder

flaskAssetsDebug: null

#: Sites to check during the status request.
statusRequestSites:
    null: null

######
# Sensitive parameters
######
#: Defines the users way may be added to the database depending on the configuration.
#: This will currently not create any users
#: Defined with an underscore since it is a private value.
#: Each user sure should added of the form user: "password"
#: If the password is not hashed, then the _users type should be
#: "!bcrypt". It will then hash all passwords that are passed
#: Also be certain to pass bcryptLogRounds for it to succeed
_users: !bcrypt
    bcryptLogRounds: *bcryptLogRounds
    null: null

#: Secret key for signing cookies
#: Defined with an underscore since it is a private value.
#: If "false" is passed, then the value will be generated automatically
#: using urandom(50), as suggested by the flask developers.
_secretKey: !secretKey false

