# coding: utf-8

"""
    PassHub API

    PassHub API documentation  # noqa: E501

    OpenAPI spec version: 1.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class UserDTO(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'activated': 'bool',
        'authorities': 'list[str]',
        'email': 'str',
        'first_name': 'str',
        'lang_key': 'str',
        'last_name': 'str',
        'login': 'str',
        'password': 'str',
        'permissions': 'list[str]'
    }

    attribute_map = {
        'activated': 'activated',
        'authorities': 'authorities',
        'email': 'email',
        'first_name': 'firstName',
        'lang_key': 'langKey',
        'last_name': 'lastName',
        'login': 'login',
        'password': 'password',
        'permissions': 'permissions'
    }

    def __init__(self, activated=None, authorities=None, email=None, first_name=None, lang_key=None, last_name=None, login=None, password=None, permissions=None):  # noqa: E501
        """UserDTO - a model defined in Swagger"""  # noqa: E501

        self._activated = None
        self._authorities = None
        self._email = None
        self._first_name = None
        self._lang_key = None
        self._last_name = None
        self._login = None
        self._password = None
        self._permissions = None
        self.discriminator = None

        if activated is not None:
            self.activated = activated
        if authorities is not None:
            self.authorities = authorities
        if email is not None:
            self.email = email
        if first_name is not None:
            self.first_name = first_name
        if lang_key is not None:
            self.lang_key = lang_key
        if last_name is not None:
            self.last_name = last_name
        if login is not None:
            self.login = login
        if password is not None:
            self.password = password
        if permissions is not None:
            self.permissions = permissions

    @property
    def activated(self):
        """Gets the activated of this UserDTO.  # noqa: E501


        :return: The activated of this UserDTO.  # noqa: E501
        :rtype: bool
        """
        return self._activated

    @activated.setter
    def activated(self, activated):
        """Sets the activated of this UserDTO.


        :param activated: The activated of this UserDTO.  # noqa: E501
        :type: bool
        """

        self._activated = activated

    @property
    def authorities(self):
        """Gets the authorities of this UserDTO.  # noqa: E501


        :return: The authorities of this UserDTO.  # noqa: E501
        :rtype: list[str]
        """
        return self._authorities

    @authorities.setter
    def authorities(self, authorities):
        """Sets the authorities of this UserDTO.


        :param authorities: The authorities of this UserDTO.  # noqa: E501
        :type: list[str]
        """

        self._authorities = authorities

    @property
    def email(self):
        """Gets the email of this UserDTO.  # noqa: E501


        :return: The email of this UserDTO.  # noqa: E501
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email):
        """Sets the email of this UserDTO.


        :param email: The email of this UserDTO.  # noqa: E501
        :type: str
        """

        self._email = email

    @property
    def first_name(self):
        """Gets the first_name of this UserDTO.  # noqa: E501


        :return: The first_name of this UserDTO.  # noqa: E501
        :rtype: str
        """
        return self._first_name

    @first_name.setter
    def first_name(self, first_name):
        """Sets the first_name of this UserDTO.


        :param first_name: The first_name of this UserDTO.  # noqa: E501
        :type: str
        """

        self._first_name = first_name

    @property
    def lang_key(self):
        """Gets the lang_key of this UserDTO.  # noqa: E501


        :return: The lang_key of this UserDTO.  # noqa: E501
        :rtype: str
        """
        return self._lang_key

    @lang_key.setter
    def lang_key(self, lang_key):
        """Sets the lang_key of this UserDTO.


        :param lang_key: The lang_key of this UserDTO.  # noqa: E501
        :type: str
        """

        self._lang_key = lang_key

    @property
    def last_name(self):
        """Gets the last_name of this UserDTO.  # noqa: E501


        :return: The last_name of this UserDTO.  # noqa: E501
        :rtype: str
        """
        return self._last_name

    @last_name.setter
    def last_name(self, last_name):
        """Sets the last_name of this UserDTO.


        :param last_name: The last_name of this UserDTO.  # noqa: E501
        :type: str
        """

        self._last_name = last_name

    @property
    def login(self):
        """Gets the login of this UserDTO.  # noqa: E501


        :return: The login of this UserDTO.  # noqa: E501
        :rtype: str
        """
        return self._login

    @login.setter
    def login(self, login):
        """Sets the login of this UserDTO.


        :param login: The login of this UserDTO.  # noqa: E501
        :type: str
        """

        self._login = login

    @property
    def password(self):
        """Gets the password of this UserDTO.  # noqa: E501


        :return: The password of this UserDTO.  # noqa: E501
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password):
        """Sets the password of this UserDTO.


        :param password: The password of this UserDTO.  # noqa: E501
        :type: str
        """

        self._password = password

    @property
    def permissions(self):
        """Gets the permissions of this UserDTO.  # noqa: E501


        :return: The permissions of this UserDTO.  # noqa: E501
        :rtype: list[str]
        """
        return self._permissions

    @permissions.setter
    def permissions(self, permissions):
        """Sets the permissions of this UserDTO.


        :param permissions: The permissions of this UserDTO.  # noqa: E501
        :type: list[str]
        """

        self._permissions = permissions

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UserDTO):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
