# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-11 19:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('durian', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipe',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group', to_field='name'),
        ),
        migrations.AlterField(
            model_name='pipe',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
