
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "06ffbc1aff9cfaff55a43af9c62dcdaa35d5c19d",
 "version": "v0.1.1-alpha.post.dev68"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
