# Generated by Django 2.0.6 on 2018-06-08 19:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tabula_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonenumberuser',
            name='demo_account',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='phonenumberuser',
            name='demo_otp',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='phonetoken',
            name='demo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='phonetoken',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
