
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-07-05T14:03:44+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "fbcc8ee75bb3992d7198a2a19185a1460266396c",
 "version": "3.0.12"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
