- project:
    check:
      jobs:
        - openstack-tox-functional
        - openstack-tox-functional-py35
        - openstack-tox-lower-constraints
    gate:
      jobs:
        - openstack-tox-functional
        - openstack-tox-functional-py35
        - openstack-tox-lower-constraints
