# Generated by Django 2.0.6 on 2018-06-25 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raceratings', '0005_auto_20180625_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagetype',
            name='allowed_types',
            field=models.CharField(choices=[('Race', 'race'), ('Home', 'home')], default=None, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='racerating',
            name='incumbent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pagetype',
            name='model_type',
            field=models.ForeignKey(limit_choices_to=models.CharField(choices=[('Race', 'race'), ('Home', 'home')], max_length=4), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
    ]
