# Generated by Django 2.0.6 on 2018-06-25 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raceratings', '0008_auto_20180625_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='racebadge',
            name='badge_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='raceratings.BadgeType'),
        ),
        migrations.AlterField(
            model_name='racebadge',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='election.Race'),
        ),
    ]
