# Generated by Django 2.0.6 on 2018-06-27 19:46

from django.db import migrations
import raceratings.fields


class Migration(migrations.Migration):

    dependencies = [
        ('raceratings', '0009_auto_20180625_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='racebadge',
            name='explanation',
            field=raceratings.fields.MarkdownField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='racerating',
            name='explanation',
            field=raceratings.fields.MarkdownField(blank=True, null=True),
        ),
    ]
