---
language: python
cache:
  - pip
  - directories:
      - "node_modules"
      - $HOME/.cache
os:
  - linux
stages:
  - lint
  - docs
  - test
  - deploy
before_install:
  # begin: workaround to enable support for py37:
  # - curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
  # - sudo apt-get install -y nodejs
  # - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
  # - echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  # - sudo apt-get update && sudo apt-get install yarn
  # - if [[ $TRAVIS_PYTHON_VERSION == '3.7-dev' ]]; then sudo add-apt-repository ppa:deadsnakes/ppa -y; fi
  # - if [[ $TRAVIS_PYTHON_VERSION == '3.7-dev' ]]; then sudo apt-get update; fi
  # sudo required only till  https://github.com/travis-ci/travis-ci/issues/9848 is fixed
  # - sudo pip install -U pip setuptools twine wheel
  # ^ end workaround
  - nvm install $TRAVIS_NODE_VERSION
  # end
  - which tox >/dev/null || if [ -z ${VIRTUAL_ENV+x} ]; then python -m pip install --user tox tox-pyenv ; else python -m pip install tox tox-pyenv; fi
notifications:
  email:
    - pycontribs@googlegroups.com
jobs:
  include:
    - stage: lint
      script:
        - python -m tox
        - npm install && npm run spell
      env: TOXENV=lint
      python: "2.7"
      language: nodejs
      node_js:
        - "8"
    - stage: docs
      script: python -m tox
      python: "2.7"
      env: TOXENV=docs
    - stage: test
      script: python -m tox
      python: "2.7"
      env: TOXENV=py27
      after_success:
        - bash <(curl -s https://codecov.io/bash) -e TOX_ENV
        - requires.io update-site -t ac3bbcca32ae03237a6aae2b02eb9411045489bb -r
    - stage: test
      script: python -m tox
      python: "3.4"
      env: TOXENV=py34
      after_success:
        - bash <(curl -s https://codecov.io/bash) -e TOX_ENV
    - stage: test
      script: python -m tox
      python: "3.5"
      env: TOXENV=py35
      after_success:
        - bash <(curl -s https://codecov.io/bash) -e TOX_ENV
    - stage: test
      script: python -m tox
      python: "3.6"
      env: TOXENV=py36 PYTHON='3.6' PYENV_VERSION='system'
      after_success:
        - bash <(curl -s https://codecov.io/bash) -e TOX_ENV
    - stage: test
      script: python -m pip install -q tox-travis && python -m tox
      python: "3.7"
      env: TOXENV=py37 PYTHON='3.7'
      after_success:
        - bash <(curl -s https://codecov.io/bash) -e TOX_ENV
      # begin: workaround to enable support for py37: https://github.com/travis-ci/travis-ci/issues/9815
      dist: xenial
      # end
    - stage: deploy
      script:
        - export PACKAGE_NAME=$(python setup.py --name)
        - export PACKAGE_VERSION=$(python setup.py --version)
        - python setup.py sdist bdist_wheel
deploy:
  - provider: pypi
    user: pycontribs
    distributions: sdist bdist_wheel
    skip_cleanup: true
    # https://github.com/travis-ci/dpl/pull/834
    edge:
      source: ssbarnea/dpl
      branch: master
    on:
      tags: true
      branch: master
      repo: pycontribs/jira
  - provider: releases
    api_key:
      secure: YJGigSNYOzMJqs23gIZLFxiVYRqHdV4WsTZmRVosishD2QIaDlTwJma7k6Y5eMPVNdLpqo7Tq6bt7xkJAz/dcr3UO35T/Y0tiRFFW3sd6IOB6ELwSwPhSeHoyUMvZtKyDTl+9tOfeZusFZuCc+mBLQcG+S2NzEaeyrQ6n5hTT/8FGBP91FOq9l5q2gYbmACZ9MisDIjZkTHNYih36ComnZ9QHC91jHKcSuHmOfWWX3GneDVFtuPhF2vjaLQrz8IFtWGW5Sfe35yDYlVQRH+NFxzSJ2zDuT5j8cRgwXjGout78umtMsqAn+zv1Ws/MUNKMTEtONsACndMpGCkuB6Nifl/KcGj5kD7V4PO/gE0ecr830qAwJxSVB7xk6rl797nMxGbr4w2DWQ/iDdHDTlPAEzbLBMLrMRgPxzKPgg5CNxxjT1cHoBNcFPp6gaf017w4XOVUgp/zxXeCg7iGiNJj7z2t8/m9eYVNNlNRPcodN6BjSjPqkYxC3ZMVCI5KsRXbHmR0zOWbPdcRjrY/IgbiTqX09sHotHw5GThP6YTMbienC4h93cdx6MEfX656W6XMOxpC+MjWtYuV8QlfMEJFlstOnA86MVLcmbl+4A6FHuvlQMdDtP9KsKdKIf/4juGhNEFir32P1rUe8J1abmjwXmDkHVbli0SDqaFtB5gyCc=
    file:
      - dist/$PACKAGE_NAME-$PACKAGE_VERSION.tar.gz
      - dist/$PACKAGE_NAME-$PACKAGE_VERSION-py2.py3-none-any.whl
      - ChangeLog
    skip_cleanup: true
    on:
      tags: true
      repo: pycontribs/jira
      branch: master
env:
  global:
    - secure: "pGQGM5YmHvOgaKihOyzb3k6bdqLQnZQ2OXO9QrfXlXwtop3zvZQi80Q+01l230x2psDWlwvqWTknAjAt1w463fYXPwpoSvKVCsLSSbjrf2l56nrDqnoir+n0CBy288+eIdaGEfzcxDiuULeKjlg08zrqjcjLjW0bDbBrlTXsb5U="
    - PIP_DISABLE_PIP_VERSION_CHECK=1
    - TRAVIS_NODE_VERSION="v8.11.3"
