SENTENCES = (
    'Took longer than I expected.',
    'Awesome product! Will buy this again.',
    'My son loves it.',
    'My daughter loves it.',
    'Exactly what I was looking for.',
    'Shipping was quite fast. I\'m really looking forward to trying this out :D',
    'It was a little bigger than I expected.',
    'Fitted perfectly.',
    'So fast.',
    'Wow!',
    'Sick.',
    'The screen size is just what I need.',
    'I like the colours.',
    'Not as large as I expected.',
    'The top is a lot brighter than in the pictures',
    'I didn\'nt even know movies could look this good!',
    'Works a treat.',
    'No service quality issues.',
    'Great deal.',
    'Great service.',
    'Great features.',
    'Great service, great product and great price',
    'This is the best deal out there.',
    'So far everything has been great.',
    'As described.',
    'The product\'s great value for money.',
    'Had it installed yesterday.',
    'Always happy with this brand.',
    'Very happy with the switch so far.',
    'I love my product.',
    'Works well and well packaged.',
    'Arrived exactly as described.',
    'So cheap and exactly the same as more expensive brands.',
    'Same product at a fraction of the price :)',
    'As good as the original.',
)
