import os


DEFAULTS = {
    'REDIS_QUEUE_PORT': 6379,
    'REDIS_RESULTS_PORT': 6379
}


class Config(object):
    REDIS_QUEUE_HOST = os.environ['REDIS_QUEUE_HOST']
    REDIS_QUEUE_PORT = os.environ.get('REDIS_QUEUE_PORT', DEFAULTS['REDIS_QUEUE_PORT'])
    REDIS_QUEUE_SERVER = "{}:{}".format(REDIS_QUEUE_HOST, REDIS_QUEUE_PORT)
    REDIS_RESULTS_HOST = os.environ['REDIS_RESULTS_HOST']
    REDIS_RESULTS_PORT = os.environ.get('REDIS_RESULTS_PORT', DEFAULTS['REDIS_RESULTS_PORT'])
    REDIS_RESULTS_SERVER = "{}:{}".format(REDIS_RESULTS_HOST, REDIS_RESULTS_PORT)
