# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jofra350', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jofra350variable',
            name='field_type',
            field=models.CharField(choices=[(b'InputValue', b'InputValue'), (b'SetFollows', b'SetFollows'), (b'StabilityRequiredSeconds', b'StabilityRequiredSeconds'), (b'StabilitySecondsLeft', b'StabilitySecondsLeft'), (b'StabilityTolerance', b'StabilityTolerance'), (b'TemperatureValue', b'TemperatureValue')], default=b'', max_length=10),
        ),
        migrations.AlterField(
            model_name='jofra350variable',
            name='sensor_type',
            field=models.CharField(choices=[(b'INT_RTD', b'Internal Reference Sensor'), (b'REF_RTD', b'External Reference Sensor')], default=b'', max_length=10),
        ),
    ]
