# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-15 09:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pyscada', '0041_update_protocol_id'),
        ('jofra350', '0005_update_protocol_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtendedJofra350Device',
            fields=[
            ],
            options={
                'verbose_name': 'Jofra350 Device',
                'proxy': True,
                'verbose_name_plural': 'Jofra350 Devices',
                'indexes': [],
            },
            bases=('pyscada.device',),
        ),
        migrations.CreateModel(
            name='ExtendedJofra350Variable',
            fields=[
            ],
            options={
                'verbose_name': 'Jofra350 Variable',
                'proxy': True,
                'verbose_name_plural': 'Jofra350 Variables',
                'indexes': [],
            },
            bases=('pyscada.variable',),
        ),
    ]
