
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-07-03T19:32:54-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "cd06ef4e15ab12178a4c79a0561b267a81683aa6",
 "version": "1.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
