- project:
    check:
      jobs:
        - solum-devstack
        - solum-devstack-centos-7
        - solum-devstack-py35
        - openstack-tox-lower-constraints
    gate:
      jobs:
        - solum-devstack

        - openstack-tox-lower-constraints
- job:
    name: solum-devstack-centos-7
    parent: legacy-dsvm-base
    run: playbooks/legacy/solum-devstack-centos-7/run.yaml
    post-run: playbooks/legacy/solum-devstack-centos-7/post.yaml
    irrelevant-files:
      - ^(test-|)requirements.txt$
      - ^setup.cfg$
      - ^doc/.*$
      - ^.*\.rst$
      - ^releasenotes/.*$
      - ^solum/tests/.*$
    voting: false
    timeout: 4200
    nodeset: legacy-centos-7
    required-projects:
      - openstack-dev/devstack
      - openstack-infra/devstack-gate
      - openstack/barbican
      - openstack/devstack-plugin-container
      - openstack/mistral
      - openstack/python-solumclient
      - openstack/python-zunclient
      - openstack/solum
      - openstack/solum-dashboard
      - openstack/zun
      - openstack/zun-tempest-plugin

- job:
    name: solum-devstack-py35
    parent: legacy-dsvm-base
    run: playbooks/legacy/solum-devstack-py35/run.yaml
    post-run: playbooks/legacy/solum-devstack-py35/post.yaml
    irrelevant-files:
      - ^(test-|)requirements.txt$
      - ^setup.cfg$
      - ^doc/.*$
      - ^.*\.rst$
      - ^releasenotes/.*$
      - ^solum/tests/.*$
    voting: false
    timeout: 4200
    required-projects:
      - openstack-dev/devstack
      - openstack-infra/devstack-gate
      - openstack/barbican
      - openstack/devstack-plugin-container
      - openstack/mistral
      - openstack/python-solumclient
      - openstack/python-zunclient
      - openstack/solum
      - openstack/solum-dashboard
      - openstack/zun
      - openstack/zun-tempest-plugin

- job:
    name: solum-devstack
    parent: legacy-dsvm-base
    run: playbooks/legacy/solum-devstack/run.yaml
    post-run: playbooks/legacy/solum-devstack/post.yaml
    irrelevant-files:
      - ^(test-|)requirements.txt$
      - ^setup.cfg$
      - ^doc/.*$
      - ^.*\.rst$
      - ^releasenotes/.*$
      - ^solum/tests/.*$
    timeout: 4200
    required-projects:
      - openstack-dev/devstack
      - openstack-infra/devstack-gate
      - openstack/barbican
      - openstack/devstack-plugin-container
      - openstack/mistral
      - openstack/python-solumclient
      - openstack/python-zunclient
      - openstack/solum
      - openstack/solum-dashboard
      - openstack/solum-tempest-plugin
      - openstack/zun
      - openstack/zun-tempest-plugin
