# coding: utf-8

"""
    BIMData API

    BIMData API documentation  # noqa: E501

    OpenAPI spec version: v1
    Contact: contact@bimdata.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import bimdata_api_client
from bimdata_api_client.models.fos_user import FosUser  # noqa: E501
from bimdata_api_client.rest import ApiException


class TestFosUser(unittest.TestCase):
    """FosUser unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFosUser(self):
        """Test FosUser"""
        # FIXME: construct object with mandatory attributes with example values
        # model = bimdata_api_client.models.fos_user.FosUser()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
