networks:
  default:
    external:
      name: vd
services:
  rails:
    image: akretion/voodoo-ruby:latest
    volumes:
      - .:/workspace
  mailcatcher:
    description: Mailcatcher is a fake mail server
    optional: True
    image: akretion/lightweight-mailcatcher
version: '2'
