language: python
python:
  - 3.5
  - 3.6
addons:
  apt:
    packages:
      - liblua5.2-dev
install:
  - pip install pytest pytest-cov codecov
script:
  - python setup.py develop
  - pytest -vv --cov=ffilupa
after_success:
  - codecov
