homeassistant:
  customize:
    group.dom_system_version:
      context_key_words: "wersja,aktualizacja,wersja systemu"
      context_answer: "OK, wybrano informację o wersji. Możesz nawigować pilotem by sprawdzić dostępność aktualizacji systemu"
      friendly_name: "Wersja systemu"
      remote_group_view: Pomoc
      order: 1
    group.dom_cloud:
      friendly_name: "Usługi AIS dom"
      order: 2
    group.system_status:
      context_key_words: "system,status systemu"
      context_answer: "OK, wybrano status systemu. Możesz nawigować pilotem by uzyskać informację o statusie elementów systemu"
      remote_group_view: Pomoc
      order: 3
    group.ais_rss_help:
      context_key_words: "instrukcja,pomoc,pomocy,help"
      context_answer: "OK, wybierz pilotem stronę pomocy"
      remote_group_view: Pomoc
      order: 4
    group.all_switches:
      order: 1
      hidden: false
      context_key_words: "przełaczniki,wszystkie przełączniki"
      context_answer: "OK, wybrano wszystkie przełączniki. Możesz powiedzieć co włączyć lub nawigować pilotem by sprawdzać status oraz przełączać."
      friendly_name: "Wszystkie przełączniki"
      remote_group_view: Twój Dom
    group.all_lights:
      order: 2
      hidden: false
      context_key_words: "światła,wszystkie światła"
      context_answer: "OK, wybrano wszystkie światła. Możesz powiedzieć co włączyć lub nawigować pilotem by sprawdzać status oraz przełączać."
      friendly_name: "Wszystkie światła"
      remote_group_view: Twój Dom
    group.all_devices:
      order: 3
      hidden: false
      context_key_words: "Urządzenia,wszystkie urządzenia"
      context_answer: "OK, urządzenia"
      friendly_name: "Wszystkie urządzenia"
      remote_group_view: Twój Dom
    group.ais_pogoda:
      remote_group_view: Twój Dom
      order: 4
    group.ais_pogoda_48:
      order: 5
      remote_group_view: Twój Dom
    group.all_automations:
      order: 6
      hidden: true
      friendly_name: "Wszystkie automatyzacje"
    group.ais_wyszukiwarka:
      order: 7
      context_key_words: "asystent,asystentka"
      context_answer: "Powiedz proszę jakie informację mam wyszukać?"
      context_suffix: "Znajdź informacje o"
      remote_group_view: Twój Dom
    group.ais_rss_news:
      order: 1
      context_key_words: "wiadomości,informacje"
      context_answer: "OK, powiedz jakie wiadomości Cię interesują lub wybierz pilotem kategorię, kanał i pozycję wuadomości"
      remote_group_view: Audio
    group.radio_player:
      context_key_words: "radio,radia,radia internetowe"
      context_answer: "OK, powiedz jakiej stacji chcesz posłuchać lub wybierz pilotem typ radia i stację radiową"
      context_suffix: "Radio"
      remote_group_view: Audio
      order: 2
    group.podcast_player:
      context_key_words: "podcast,podcasty,podkasty,podkast"
      context_answer: "OK, powiedz jaką audycję mam włączyć lub wybierz pilotem typ, audycję i odcinek podcasta"
      context_suffix: "Podcast"
      remote_group_view: Audio
      order: 3
    group.music_player:
      context_key_words: "youtube,muzyka,yt,tuba"
      context_answer: "OK, powiedz jakiej muzyki chcesz posłuchać?"
      context_suffix: "Muzyka"
      remote_group_view: Audio
      order: 4
    group.audiobooks_player:
      context_key_words: "książki,książka,audiobook,audiobooks"
      context_answer: "OK, powiedz jakiej książki chcesz posłuchać lub wybierz pilotem autora, książkę i rozdział książki"
      context_suffix: "Książka"
      remote_group_view: Audio
      order: 5
    group.audio_player:
      context_key_words: "odtwarzacz, odtwarzacze"
      context_answer: "OK, wybrano odtwarzacz."
      order: 6
      remote_group_view: Audio
    group.internet_status:
      context_key_words: "internet,sieć,ustawienia sieci,wifi"
      context_answer: "OK, wybrano internet. Możesz nawigowac pilotem by uzyskać informację o statusie Twojej sieci."
      remote_group_view: Ustawienia
      order: 1
    group.ais_add_iot_device:
      context_key_words: "dodaj urządzenie"
      context_answer: "OK, wybrano dodawanie nowego urządzenia. Możesz nawigowac pilotem by dodać urządzenie do systemu."
      remote_group_view: Ustawienia
      order: 2
    group.ais_tts_configuration:
      context_key_words: "głos,ustawienia głosu"
      context_answer: "OK, wybrano konfigurację zamiany tekstu na mowę"
      remote_group_view: Ustawienia
      order: 3


group:
  default_view:
    view: yes
    icon: mdi:home-outline
    entities:
      - sensor.time
      - sensor.date_formated
      - sun.sun
      - sensor.temperatura_si7021
      - sensor.wilgotnosc_si7021
      - group.ais_wyszukiwarka
      - media_player.wbudowany_glosnik
      - sensor.pogoda_symbol
      - group.all_switches
      - group.all_lights
      - group.all_automations
  pogoda:
    name: Pogoda
    view: yes
    icon: mdi:weather-partlycloudy
    entities:
      - group.day_info
      - group.ais_pogoda
      - group.ais_pogoda_48
      # - weather.pogoda_z_openweathermap
      # - sensor.airly_aqi
      # - sensor.airly_pm10
      # - sensor.airly_pm25
  audio_player:
    name: Odtwarzacz
    entities:
      - media_player.wbudowany_glosnik
      - input_number.media_player_speed
  news:
    name: wiadomości
    view: yes
    icon: mdi:newspaper
    entities:
      - group.ais_rss_news
  audio:
    name: audio
    view: yes
    icon:  mdi:music
    entities:
      - group.radio_player
      - group.podcast_player
      - group.music_player
      - group.audiobooks_player
      - group.audio_player
  setings:
    name: setings
    view: yes
    icon:  mdi:account-settings-variant
    entities:
      - group.ais_tts_configuration
      - group.internet_status
      - group.ais_add_iot_device
  pomoc:
      name: Pomoc
      view: yes
      icon: mdi:help
      entities:
        - group.dom_system_version
        - group.ais_rss_help
        # - group.ais_android_certification
        - group.dom_cloud
  system:
      name: System
      view: yes
      icon: mdi:console
      entities:
        - group.ais_pilot
        - group.ais_dev_ssh
        - group.ais_host_rename
        - group.system_status
        - group.ais_devices_in_network
