site_name: hexpy
site_description: A Python client for the Crimson Hexagon API.
repo_url: https://github.com/sullivancolin/hexpy
pages:
    - Home: index.md
    - Session: Session.md
    - Metadata: Metadata.md
    - Monitor: Monitor.md
    - Analysis: Analysis.md
    - Upload: Upload.md
    - Streams: Streams.md
    - Realtime: Realtime.md
    - Custom: Custom.md
    - Activty Reports: Activity.md
    - Command Line Interface: CLI.md
    - Crimson Api Documentation: crimson_api_docs.md
theme: 'material'
extra:
    version: 0.5.0
