from argparse import ArgumentParser


DESCRIPTION = 'In order to run an application container with Curious Containers, CC-Agency will launch CC-Agent in ' \
              'connected mode. The agent sends the container\'s internal status to the server and receives ' \
              'instructions.'


def attach_args(parser):
    parser.add_argument(
        'callback_url', action='store', type=str, metavar='CALLBACK_URL',
        help='An individual CALLBACK_URL is generated by CC-Server for the corresponding agent.'
    )


def main():
    parser = ArgumentParser(description=DESCRIPTION)
    attach_args(parser)
    args = parser.parse_args()
    return run(**args.__dict__)


def run(callback_url):
    print(callback_url)
    return 0
