
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-07-10T16:44:27-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "1a5ce2828714fc0e34780ac866532d4106d1a05b",
 "version": "1.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
