networks:
  default:
    external:
      name: vd
services:
  mariadb:
    optional: Add magento server (with connector) ?
    image: paintedfox/mariadb
    environment:
      - USER=magento
      - PASS=magento
    ports:
      - 3306:3306
    volumes:
      - .mariadb/data/:/data
  magento:
    optional: Add magento server (with connector) ?
    environment:
    - DB_ENV_USER=magento
    - DB_ENV_PASS=magento
    expose: 80
    image: akretion/docker-magento
    ports:
      - 80:80
    links:
      - mariadb:db
      - memcached:cache
    volumes:
      - .magento/firstrun:/firstrun
      - .magento/www:/var/www
  memcached:
    optional: Add magento server (with connector) ?
    image: sylvainlasnier/memcached
    ports:
      - 11211:11211
  py3ofusion:
    optional: Add py3o reports server
    image: xcgd/py3o.fusion
    ports:
        - "8765:8765"
    links:
        - "py3orenderserver"
  py3orenderserver:
    optional: Add py3o reports server
    image: xcgd/py3oserver-docker
    links:
        - "oooserver"
    volumes_from:
        - "oooserver"
  oooserver:
    optional: Add py3o reports server
    image: xcgd/libreoffice
  metabase:
    optional: metabase is Web tools for BI with dashboard
    expose: 3000
    image: metabase/metabase
    environment:
    - MB_DB_FILE=/file/metabase.db
    links:
    - db
    volumes:
    - .:/file
  firefox:
    optional: Selenium Standalone with Firefox installed and runs a VNC server
    hostname: firefox
    image: "selenium/standalone-firefox-debug"
    ports:
    - "4444:4444"
    - "5900:5900"
    volumes:
    - /dev/shm:/dev/shm
  pgadmin:
    optional: Pgadmin v4 is postgresql Web GUI
    expose: 5050
    image: fenglc/pgadmin4
    links:
      - db
  adminer:
    optional: Adminer, RDBMS Web GUI (including Postgresql) with usability and perf
    image: adminer
    expose: 8080
    links:
      - db
  db:
    image: quay.io/akretion/postgresql:10
    environment:
    - POSTGRES_USER=odoo
    - POSTGRES_DB=db
    volumes:
    - .db/data/:/var/lib/postgresql/data
    - .db/socket/:/var/run/postgresql/
  mailcatcher:
    optional: Mailcatcher is a fake mail server
    expose: 1080
    image: akretion/lightweight-mailcatcher
  odoo:
    build: .
    expose: 8069
    environment:
    - PYTHONDONTWRITEBYTECODE=True
    links:
    - db
    volumes:
    - .:/workspace
    - .db/socket/:/var/run/postgresql/
version: '2'
