- project:
    check:
      jobs:
        - oslo.versionedobjects-src-grenade-devstack-multinode

        - openstack-tox-lower-constraints
    gate:
      jobs:
        - openstack-tox-lower-constraints
- job:
    name: oslo.versionedobjects-src-grenade-devstack-multinode
    parent: legacy-dsvm-base-multinode
    voting: false
    irrelevant-files:
      - ^(test-|)requirements.txt$
      - ^setup.cfg$
    run: playbooks/legacy/oslo.versionedobjects-src-grenade-devstack-multinode/run.yaml
    post-run: playbooks/legacy/oslo.versionedobjects-src-grenade-devstack-multinode/post.yaml
    timeout: 10800
    required-projects:
      - openstack-dev/grenade
      - openstack-infra/devstack-gate
      - openstack/oslo.versionedobjects
    nodeset: legacy-ubuntu-xenial-2-node
