
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-06-28T14:07:56+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "6c6f1e73376fe8f1ded4fc9ddec8ffbb270ee652",
 "version": "0.2.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
