image: mgoral/super-ci-runner:latest

stages:
    - test
    - publish
    - pypi

before_script:
    - pip3 install tox

test:
    stage: test
    script:
        - tox -e py35
        - tox -e py36

test-coverage:
    stage: test
    script:
        - tox -e coverage
    artifacts:
        name: coverage
        expire_in: 30 days
        paths:
            - coverage.xml
            - htmlcov/
    allow_failure: true

pages:
    stage: publish
    before_script:
        - pwd
    dependencies:
        - test-coverage
    script:
        - mv htmlcov/ public/
    artifacts:
        paths:
            - public
        expire_in: 30 days
    only:
        - master
    allow_failure: true

dist:
    stage: pypi
    before_script:
        - pip3 install -rreqs/requirements-deploy.txt
    only:
        - tags
        - triggers
    script:
        # https://github.com/pypa/setuptools/issues/1064
        - python3 setup.py sdist
        - python3 setup.py bdist_wheel
        - twine upload dist/* -u "$PYPI_USER" -p "$PYPI_PASS"
    artifacts:
        name: "${CI_PROJECT_NAME}-{$CI_BUILD_REF_NAME}"
        paths:
            - dist/
