# Generated by Django 2.0.6 on 2018-06-25 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raceratings', '0003_auto_20180625_1536'),
    ]

    operations = [
        migrations.RenameField(
            model_name='racerating',
            old_name='blurb',
            new_name='explanation',
        ),
    ]
