# Generated by Django 2.0.6 on 2018-06-25 15:51

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raceratings', '0004_auto_20180625_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='racebadge',
            name='explanation',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=[], null=True),
        ),
    ]
