# Generated by Django 2.0.6 on 2018-06-25 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raceratings', '0006_auto_20180625_1751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagetype',
            name='allowed_types',
        ),
        migrations.AlterField(
            model_name='pagetype',
            name='model_type',
            field=models.CharField(choices=[('Race', 'race'), ('Home', 'home')], max_length=4),
        ),
    ]
