# One endpoint settings
one:
  name: One
  host: https://raw.githubusercontent.com/tadashi-aikawa/jumeaux-toolbox/master/vagrant/simple/one

# The other endpoint settings
other:
  name: Other
  host: https://raw.githubusercontent.com/tadashi-aikawa/jumeaux-toolbox/master/vagrant/simple/other

# Output path for API responses
output:
  response_dir: responses

# Add-ons to use. See https://tadashi-aikawa.github.io/jumeaux/ja/addons
addons:
  log2reqs:
    name: plain

  res2dict:
    - name: json
      config:
        # Usually, we don't need to set `mime_types`
        # In this case, `raw.githubusercontent.com` always return `mime-type: text/plain` even if response is json.
        # So we need to specify `mime_types` as following now.
        mime_types: [text/plain]

  dump:
    - name: json
      config:
        # Usually, we don't need to set `mime_types`
        # In this case, `raw.githubusercontent.com` always return `mime-type: text/plain` even if response is json.
        # So we need to specify `mime_types` as following now.
        mime_types: [text/plain]

  store_criterion:
    # Store different responses
    - name: general
      config:
        statuses:
          - different
