# {# pkglts, travis
# Config file for automatic testing at travis-ci.org

language: python

python:
{%- for pyver in pysetup.intended_versions %}
  - "{{ pyver[0] }}.{{ pyver[1] }}"
{%- endfor %}

# #}

addons:
  apt:
    packages:
# {# pkglts, travis.addons
# #}

install:
# {# pkglts, travis.install
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  - conda create -q -n myenv python=$TRAVIS_PYTHON_VERSION
  - source activate myenv

{% for dep in pysetup.requirements('install') %}
  {%- if dep.is_conda(strict=False) %}
  - {{ dep.conda_install() }}
  {%- elif dep.is_pip(strict=True) %}
  - {{ dep.pip_install() }}
  {%- elif dep.package_manager == 'git' %}
  - pip install git+https://github.com/{{ dep.name }}
  {%- endif %}
{%- endfor %}

{%- for dep in pysetup.requirements('dvlpt') %}
  {%- if dep.is_conda(strict=False) %}
  - {{ dep.conda_install() }}
  {%- elif dep.is_pip(strict=True) %}
  - {{ dep.pip_install() }}
  {%- elif dep.package_manager == 'git' %}
  - pip install git+https://github.com/{{ dep.name }}
  {%- endif %}
{%- endfor %}

  - python setup.py install
# #}

script:
# {# pkglts, travis.script
  {%- if 'test' is available -%}
  {%- if test.suite_name == 'nose' %}
  - nosetests
  {%- endif -%}
  {%- if test.suite_name == 'pytest' %}
  - pytest
  {%- endif -%}
  {%- endif %}
# #}

after_success:
# {# pkglts, travis.after
{%- if 'coveralls' is available -%}
  - coveralls
{%- endif %}
# #}
