
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-07-12T11:34:00-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "2b25cda8f5b8f38e8c0d2961161d9ba36b9aa5f6",
 "version": "0.41.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
