# coding: utf-8
from __future__ import absolute_import


# 1 and 2 are used by `argparse`.
MAIN_RET_V_PSR_TPLT_FILE_READ_ERR = 3
MAIN_RET_V_EXT_OPTS_LOAD_ERR = 4
MAIN_RET_V_RULES_FILE_READ_ERR = 5
MAIN_RET_V_RULES_OBJ_LOAD_ERR = 6
MAIN_RET_V_RULES_OBJ_NOT_STR_ERR = 7
MAIN_RET_V_RULES_PARSE_ERR = 8
MAIN_RET_V_SRC_FILE_READ_ERR = 9
MAIN_RET_V_SRC_OBJ_LOAD_ERR = 10
MAIN_RET_V_SRC_OBJ_NOT_STR_ERR = 11
MAIN_RET_V_PSR_CODE_WRITE_FILE_ERR = 12
MAIN_RET_V_PSR_CODE_LOAD_ERR = 13
MAIN_RET_V_PSR_CODE_CALL_ERR = 14
