from .base import BaseField


class BytesField(BaseField):
    TYPE = ...
    DEFAULT = ...

    def from_python(self, value) -> bytes: ...
    def to_python(self, value) -> bytes: ...


class StringField(BytesField):
    DEFAULT = ...

    def from_python(self, value) -> bytes: ...
    def to_python(self, value) -> str: ...
