import ipaddress
from typing import Union

from .integer_field import UInt64Field, UInt32Field


class IPv6Field(UInt64Field):
    DEFAULT = ...

    def from_python(self, value: Union[ipaddress.IPv6Address, str]) -> int: ...
    def to_python(self, value) -> ipaddress.IPv6Address: ...


class IPv4Field(UInt32Field):
    DEFAULT = ...

    def from_python(self, value: Union[ipaddress.IPv4Address, str]) -> int: ...
    def to_python(self, value: int) -> ipaddress.IPv4Address: ...
