


CT_PostgresQL:
  host: 10.180.10.181
  port: 5432
  database: ramp

Uqer:
  token:

Wind_Oracle:
  user: rwind
  password: rwind
  host: 10.180.10.139
  port: 1521
  database: WINDB


Gogoal_Oracle:
  user: gogousr
  password: gogousr123
  host: 10.180.10.179
  port: 1521
  database: GOGODB


XRisk_Oracle:
  user:
  password:
  host: 10.180.10.129
  port: 1521
  database: ASSET


Email_Setting:
  sender:
  receiver:
  username:
  password:
  host:

Remote_Folder:
  user:
  password:
  host: 10.180.10.181
  port: 22


