# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-30 10:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navsy', '0017_renamed_page_route_fields_with_is_prefix'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='route',
            options={'ordering': ['page', '-priority'], 'verbose_name': 'Route', 'verbose_name_plural': 'Routes'},
        ),
    ]
