# coding: utf-8

"""
    PassHub API

    PassHub API documentation  # noqa: E501

    OpenAPI spec version: 1.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class Address(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'city': 'str',
        'company': 'str',
        'country': 'str',
        'email': 'str',
        'name': 'str',
        'phone': 'str',
        'residential': 'bool',
        'state': 'str',
        'street1': 'str',
        'street2': 'str',
        'zip': 'str',
        'zip4': 'str'
    }

    attribute_map = {
        'city': 'city',
        'company': 'company',
        'country': 'country',
        'email': 'email',
        'name': 'name',
        'phone': 'phone',
        'residential': 'residential',
        'state': 'state',
        'street1': 'street1',
        'street2': 'street2',
        'zip': 'zip',
        'zip4': 'zip4'
    }

    def __init__(self, city=None, company=None, country=None, email=None, name=None, phone=None, residential=None, state=None, street1=None, street2=None, zip=None, zip4=None):  # noqa: E501
        """Address - a model defined in Swagger"""  # noqa: E501

        self._city = None
        self._company = None
        self._country = None
        self._email = None
        self._name = None
        self._phone = None
        self._residential = None
        self._state = None
        self._street1 = None
        self._street2 = None
        self._zip = None
        self._zip4 = None
        self.discriminator = None

        if city is not None:
            self.city = city
        if company is not None:
            self.company = company
        if country is not None:
            self.country = country
        if email is not None:
            self.email = email
        if name is not None:
            self.name = name
        if phone is not None:
            self.phone = phone
        if residential is not None:
            self.residential = residential
        if state is not None:
            self.state = state
        if street1 is not None:
            self.street1 = street1
        if street2 is not None:
            self.street2 = street2
        if zip is not None:
            self.zip = zip
        if zip4 is not None:
            self.zip4 = zip4

    @property
    def city(self):
        """Gets the city of this Address.  # noqa: E501


        :return: The city of this Address.  # noqa: E501
        :rtype: str
        """
        return self._city

    @city.setter
    def city(self, city):
        """Sets the city of this Address.


        :param city: The city of this Address.  # noqa: E501
        :type: str
        """

        self._city = city

    @property
    def company(self):
        """Gets the company of this Address.  # noqa: E501


        :return: The company of this Address.  # noqa: E501
        :rtype: str
        """
        return self._company

    @company.setter
    def company(self, company):
        """Sets the company of this Address.


        :param company: The company of this Address.  # noqa: E501
        :type: str
        """

        self._company = company

    @property
    def country(self):
        """Gets the country of this Address.  # noqa: E501


        :return: The country of this Address.  # noqa: E501
        :rtype: str
        """
        return self._country

    @country.setter
    def country(self, country):
        """Sets the country of this Address.


        :param country: The country of this Address.  # noqa: E501
        :type: str
        """

        self._country = country

    @property
    def email(self):
        """Gets the email of this Address.  # noqa: E501


        :return: The email of this Address.  # noqa: E501
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email):
        """Sets the email of this Address.


        :param email: The email of this Address.  # noqa: E501
        :type: str
        """

        self._email = email

    @property
    def name(self):
        """Gets the name of this Address.  # noqa: E501


        :return: The name of this Address.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Address.


        :param name: The name of this Address.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def phone(self):
        """Gets the phone of this Address.  # noqa: E501


        :return: The phone of this Address.  # noqa: E501
        :rtype: str
        """
        return self._phone

    @phone.setter
    def phone(self, phone):
        """Sets the phone of this Address.


        :param phone: The phone of this Address.  # noqa: E501
        :type: str
        """

        self._phone = phone

    @property
    def residential(self):
        """Gets the residential of this Address.  # noqa: E501


        :return: The residential of this Address.  # noqa: E501
        :rtype: bool
        """
        return self._residential

    @residential.setter
    def residential(self, residential):
        """Sets the residential of this Address.


        :param residential: The residential of this Address.  # noqa: E501
        :type: bool
        """

        self._residential = residential

    @property
    def state(self):
        """Gets the state of this Address.  # noqa: E501


        :return: The state of this Address.  # noqa: E501
        :rtype: str
        """
        return self._state

    @state.setter
    def state(self, state):
        """Sets the state of this Address.


        :param state: The state of this Address.  # noqa: E501
        :type: str
        """

        self._state = state

    @property
    def street1(self):
        """Gets the street1 of this Address.  # noqa: E501


        :return: The street1 of this Address.  # noqa: E501
        :rtype: str
        """
        return self._street1

    @street1.setter
    def street1(self, street1):
        """Sets the street1 of this Address.


        :param street1: The street1 of this Address.  # noqa: E501
        :type: str
        """

        self._street1 = street1

    @property
    def street2(self):
        """Gets the street2 of this Address.  # noqa: E501


        :return: The street2 of this Address.  # noqa: E501
        :rtype: str
        """
        return self._street2

    @street2.setter
    def street2(self, street2):
        """Sets the street2 of this Address.


        :param street2: The street2 of this Address.  # noqa: E501
        :type: str
        """

        self._street2 = street2

    @property
    def zip(self):
        """Gets the zip of this Address.  # noqa: E501


        :return: The zip of this Address.  # noqa: E501
        :rtype: str
        """
        return self._zip

    @zip.setter
    def zip(self, zip):
        """Sets the zip of this Address.


        :param zip: The zip of this Address.  # noqa: E501
        :type: str
        """

        self._zip = zip

    @property
    def zip4(self):
        """Gets the zip4 of this Address.  # noqa: E501


        :return: The zip4 of this Address.  # noqa: E501
        :rtype: str
        """
        return self._zip4

    @zip4.setter
    def zip4(self, zip4):
        """Sets the zip4 of this Address.


        :param zip4: The zip4 of this Address.  # noqa: E501
        :type: str
        """

        self._zip4 = zip4

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Address):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
