
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "2c8f3a1c72437a7fc1644342aeaa7a516ca4a0ce",
 "version": "3.0.0rc3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
