
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "d9ebce47b4f9d9ed48e6b230113a281f5d0915ec",
 "version": "1.0.0.post.dev742"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
