
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-06-20T23:39:12-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "b12921b9cc4dbcc5c1784ff7c6a38d1824130362",
 "version": "0.0.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
