sudo: false
addons:
  apt:
    packages:
    - rpm
language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install tox tox-travis coveralls
script:
  - tox
after_success:
  - coveralls
