#-*- coding: utf-8 -*-
# This file is automatically generated by 'setup.py'
"""
Created on 2017-01-05 20:53:15
Modified on 2018-06-17 01:58:06

@author: Young Ju Kim
"""
__all__ = ['__version__']


__version__ = '0.0.4.18'

