image: ikus060/docker-debian-py2-py3:stretch

stages:
- test
- publish

# Upgrade python and install dependencies to avoid compiling from sources.
before_script:
- apt-get update && apt-get -qq install python-pysqlite2 libldap2-dev libsasl2-dev rdiff-backup node-less
- pip install pip setuptools --upgrade

.tox:  &tox
  stage: test
  script:
  - pip install tox nose coverage --upgrade
  - tox -e $CI_JOB_NAME --sitepackages
  artifacts:
    paths:
    - .coverage.$CI_JOB_NAME
    expire_in: 1 day

py27-cherrypy35: 
  <<: *tox
  
py27-cherrypy4: 
  <<: *tox
  
py27-cherrypy5: 
  <<: *tox
  
py27-cherrypy6: 
  <<: *tox
  
py27-cherrypy7: 
  <<: *tox
  
py27-cherrypy8: 
  <<: *tox
  
py27-cherrypy9: 
  <<: *tox
  
py27-cherrypy10: 
  <<: *tox
  
py27-cherrypy11: 
  <<: *tox
  
py27-cherrypy12: 
  <<: *tox
  
py27-cherrypy13:  
  <<: *tox
  
py27-cherrypy14: 
  <<: *tox

py27-cherrypy15: 
  <<: *tox
  
py27-cherrypy16: 
  <<: *tox
  
py3-cherrypy35: 
  <<: *tox
  
py3-cherrypy4: 
  <<: *tox
  
py3-cherrypy5: 
  <<: *tox
  
py3-cherrypy6: 
  <<: *tox
  
py3-cherrypy7: 
  <<: *tox
  
py3-cherrypy8: 
  <<: *tox
  
py3-cherrypy9: 
  <<: *tox
  
py3-cherrypy10: 
  <<: *tox
  
py3-cherrypy11: 
  <<: *tox
  
py3-cherrypy12: 
  <<: *tox
  
py3-cherrypy13: 
  <<: *tox
  
py3-cherrypy14: 
  <<: *tox

py3-cherrypy15: 
  <<: *tox
  
py3-cherrypy16: 
  <<: *tox
  
py27-cherrypy32: 
  <<: *tox

# TODO Publish coverage repport
# TODO Publish testcases repport

publish_nexus:
  stage: publish
  script:
  - pip install wheel twine --upgrade
  - python setup.py sdist bdist_wheel
  - twine upload dist/* -u $NEXUS_USR -p $NEXUS_PWD --repository-url $NEXUS_PYPI_URL

publish_pypi:
  stage: publish
  only:
  - tags
  script:
  - pip install wheel twine --upgrade
  - python setup.py sdist bdist_wheel
  - twine upload dist/* -u $PYPI_USR -p $PYPI_PWD
  
github_push:
  stage: publish
  only:
  - branches
  script:
  - git push --force https://${GITHUB_USR}:${GITHUB_PWD}@github.com/ikus060/rdiffweb.git refs/remotes/origin/${CI_COMMIT_REF_NAME}:refs/heads/${CI_COMMIT_REF_NAME}
  - git push https://${GITHUB_USR}:${GITHUB_PWD}@github.com/ikus060/rdiffweb.git --tags

