# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: capsule8/api/v0/event_service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.rpc import status_pb2 as google_dot_rpc_dot_status__pb2
from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from capsule8.api.v0 import event_pb2 as capsule8_dot_api_dot_v0_dot_event__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='capsule8/api/v0/event_service.proto',
  package='capsule8.api.v0',
  syntax='proto3',
  serialized_pb=_b('\n#capsule8/api/v0/event_service.proto\x12\x0f\x63\x61psule8.api.v0\x1a\x17google/rpc/status.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1b\x63\x61psule8/api/v0/event.proto\";\n\x12\x43reateEventRequest\x12%\n\x05\x65vent\x18\x01 \x01(\x0b\x32\x16.capsule8.api.v0.Event\"9\n\x13\x43reateEventResponse\x12\"\n\x06status\x18\x01 \x01(\x0b\x32\x12.google.rpc.Status\"\x81\x01\n\x12WatchEventsRequest\x12.\n\nstart_time\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12,\n\x08\x65nd_time\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\r\n\x05limit\x18\x03 \x01(\x04\"`\n\x13WatchEventsResponse\x12\"\n\x06status\x18\x01 \x01(\x0b\x32\x12.google.rpc.Status\x12%\n\x05\x65vent\x18\x02 \x01(\x0b\x32\x16.capsule8.api.v0.Event2\xef\x01\n\x0c\x45ventService\x12o\n\x0b\x43reateEvent\x12#.capsule8.api.v0.CreateEventRequest\x1a$.capsule8.api.v0.CreateEventResponse\"\x15\x82\xd3\xe4\x93\x02\x0f\"\n/v0/events:\x01*\x12n\n\x0bWatchEvents\x12#.capsule8.api.v0.WatchEventsRequest\x1a$.capsule8.api.v0.WatchEventsResponse\"\x12\x82\xd3\xe4\x93\x02\x0c\x12\n/v0/events0\x01\x42\x1cZ\x1agithub.com/capsule8/api/v0b\x06proto3')
  ,
  dependencies=[google_dot_rpc_dot_status__pb2.DESCRIPTOR,google_dot_api_dot_annotations__pb2.DESCRIPTOR,google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,capsule8_dot_api_dot_v0_dot_event__pb2.DESCRIPTOR,])




_CREATEEVENTREQUEST = _descriptor.Descriptor(
  name='CreateEventRequest',
  full_name='capsule8.api.v0.CreateEventRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='event', full_name='capsule8.api.v0.CreateEventRequest.event', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=173,
  serialized_end=232,
)


_CREATEEVENTRESPONSE = _descriptor.Descriptor(
  name='CreateEventResponse',
  full_name='capsule8.api.v0.CreateEventResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='capsule8.api.v0.CreateEventResponse.status', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=234,
  serialized_end=291,
)


_WATCHEVENTSREQUEST = _descriptor.Descriptor(
  name='WatchEventsRequest',
  full_name='capsule8.api.v0.WatchEventsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='start_time', full_name='capsule8.api.v0.WatchEventsRequest.start_time', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='end_time', full_name='capsule8.api.v0.WatchEventsRequest.end_time', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='limit', full_name='capsule8.api.v0.WatchEventsRequest.limit', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=294,
  serialized_end=423,
)


_WATCHEVENTSRESPONSE = _descriptor.Descriptor(
  name='WatchEventsResponse',
  full_name='capsule8.api.v0.WatchEventsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='capsule8.api.v0.WatchEventsResponse.status', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='event', full_name='capsule8.api.v0.WatchEventsResponse.event', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=425,
  serialized_end=521,
)

_CREATEEVENTREQUEST.fields_by_name['event'].message_type = capsule8_dot_api_dot_v0_dot_event__pb2._EVENT
_CREATEEVENTRESPONSE.fields_by_name['status'].message_type = google_dot_rpc_dot_status__pb2._STATUS
_WATCHEVENTSREQUEST.fields_by_name['start_time'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_WATCHEVENTSREQUEST.fields_by_name['end_time'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_WATCHEVENTSRESPONSE.fields_by_name['status'].message_type = google_dot_rpc_dot_status__pb2._STATUS
_WATCHEVENTSRESPONSE.fields_by_name['event'].message_type = capsule8_dot_api_dot_v0_dot_event__pb2._EVENT
DESCRIPTOR.message_types_by_name['CreateEventRequest'] = _CREATEEVENTREQUEST
DESCRIPTOR.message_types_by_name['CreateEventResponse'] = _CREATEEVENTRESPONSE
DESCRIPTOR.message_types_by_name['WatchEventsRequest'] = _WATCHEVENTSREQUEST
DESCRIPTOR.message_types_by_name['WatchEventsResponse'] = _WATCHEVENTSRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CreateEventRequest = _reflection.GeneratedProtocolMessageType('CreateEventRequest', (_message.Message,), dict(
  DESCRIPTOR = _CREATEEVENTREQUEST,
  __module__ = 'capsule8.api.v0.event_service_pb2'
  # @@protoc_insertion_point(class_scope:capsule8.api.v0.CreateEventRequest)
  ))
_sym_db.RegisterMessage(CreateEventRequest)

CreateEventResponse = _reflection.GeneratedProtocolMessageType('CreateEventResponse', (_message.Message,), dict(
  DESCRIPTOR = _CREATEEVENTRESPONSE,
  __module__ = 'capsule8.api.v0.event_service_pb2'
  # @@protoc_insertion_point(class_scope:capsule8.api.v0.CreateEventResponse)
  ))
_sym_db.RegisterMessage(CreateEventResponse)

WatchEventsRequest = _reflection.GeneratedProtocolMessageType('WatchEventsRequest', (_message.Message,), dict(
  DESCRIPTOR = _WATCHEVENTSREQUEST,
  __module__ = 'capsule8.api.v0.event_service_pb2'
  # @@protoc_insertion_point(class_scope:capsule8.api.v0.WatchEventsRequest)
  ))
_sym_db.RegisterMessage(WatchEventsRequest)

WatchEventsResponse = _reflection.GeneratedProtocolMessageType('WatchEventsResponse', (_message.Message,), dict(
  DESCRIPTOR = _WATCHEVENTSRESPONSE,
  __module__ = 'capsule8.api.v0.event_service_pb2'
  # @@protoc_insertion_point(class_scope:capsule8.api.v0.WatchEventsResponse)
  ))
_sym_db.RegisterMessage(WatchEventsResponse)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('Z\032github.com/capsule8/api/v0'))

_EVENTSERVICE = _descriptor.ServiceDescriptor(
  name='EventService',
  full_name='capsule8.api.v0.EventService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=524,
  serialized_end=763,
  methods=[
  _descriptor.MethodDescriptor(
    name='CreateEvent',
    full_name='capsule8.api.v0.EventService.CreateEvent',
    index=0,
    containing_service=None,
    input_type=_CREATEEVENTREQUEST,
    output_type=_CREATEEVENTRESPONSE,
    options=_descriptor._ParseOptions(descriptor_pb2.MethodOptions(), _b('\202\323\344\223\002\017\"\n/v0/events:\001*')),
  ),
  _descriptor.MethodDescriptor(
    name='WatchEvents',
    full_name='capsule8.api.v0.EventService.WatchEvents',
    index=1,
    containing_service=None,
    input_type=_WATCHEVENTSREQUEST,
    output_type=_WATCHEVENTSRESPONSE,
    options=_descriptor._ParseOptions(descriptor_pb2.MethodOptions(), _b('\202\323\344\223\002\014\022\n/v0/events')),
  ),
])
_sym_db.RegisterServiceDescriptor(_EVENTSERVICE)

DESCRIPTOR.services_by_name['EventService'] = _EVENTSERVICE

# @@protoc_insertion_point(module_scope)
