# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: capsule8/api/v0/pubsub_service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='capsule8/api/v0/pubsub_service.proto',
  package='capsule8.api.v0',
  syntax='proto3',
  serialized_pb=_b('\n$capsule8/api/v0/pubsub_service.proto\x12\x0f\x63\x61psule8.api.v0\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"1\n\x0ePublishRequest\x12\r\n\x05topic\x18\x01 \x01(\t\x12\x10\n\x08messages\x18\x02 \x03(\x0c\"J\n\x0fPublishResponse\x12\x37\n\x0f\x66\x61iled_messages\x18\x01 \x03(\x0b\x32\x1e.capsule8.api.v0.FailedMessage\"/\n\rFailedMessage\x12\x0f\n\x07payload\x18\x01 \x01(\x0c\x12\r\n\x05\x65rror\x18\x02 \x01(\t\"e\n\x0bPullRequest\x12\r\n\x05topic\x18\x01 \x01(\t\x12\x0f\n\x07timeout\x18\x02 \x01(\x03\x12*\n\x04time\x18\t \x01(\x0b\x32\x1a.google.protobuf.TimestampH\x00\x42\n\n\x08start_at\"B\n\x0cPullResponse\x12\x32\n\x08messages\x18\x01 \x03(\x0b\x32 .capsule8.api.v0.ReceivedMessage\"~\n\x0fReceivedMessage\x12\x0b\n\x03\x61\x63k\x18\x01 \x01(\x0c\x12\x0f\n\x07payload\x18\x02 \x01(\x0c\x12\x1b\n\x13publish_time_micros\x18\x03 \x01(\x03\x12\x30\n\x0cpublish_time\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\"\n\x12\x41\x63knowledgeRequest\x12\x0c\n\x04\x61\x63ks\x18\x01 \x03(\x0c\"*\n\x13\x41\x63knowledgeResponse\x12\x13\n\x0b\x66\x61iled_acks\x18\x01 \x03(\x0c\x32\xcb\x02\n\rPubsubService\x12j\n\x07Publish\x12\x1f.capsule8.api.v0.PublishRequest\x1a .capsule8.api.v0.PublishResponse\"\x1c\x82\xd3\xe4\x93\x02\x16\"\x11/v0/topic/{topic}:\x01*\x12`\n\x04Pull\x12\x1c.capsule8.api.v0.PullRequest\x1a\x1d.capsule8.api.v0.PullResponse\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/v0/topic/{topic}0\x01\x12l\n\x0b\x41\x63knowledge\x12#.capsule8.api.v0.AcknowledgeRequest\x1a$.capsule8.api.v0.AcknowledgeResponse\"\x12\x82\xd3\xe4\x93\x02\x0c\"\x07/v0/ack:\x01*B\x1cZ\x1agithub.com/capsule8/api/v0b\x06proto3')
  ,
  dependencies=[google_dot_api_dot_annotations__pb2.DESCRIPTOR,google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_PUBLISHREQUEST = _descriptor.Descriptor(
  name='PublishRequest',
  full_name='capsule8.api.v0.PublishRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='topic', full_name='capsule8.api.v0.PublishRequest.topic', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='messages', full_name='capsule8.api.v0.PublishRequest.messages', index=1,
      number=2, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=120,
  serialized_end=169,
)


_PUBLISHRESPONSE = _descriptor.Descriptor(
  name='PublishResponse',
  full_name='capsule8.api.v0.PublishResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='failed_messages', full_name='capsule8.api.v0.PublishResponse.failed_messages', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=171,
  serialized_end=245,
)


_FAILEDMESSAGE = _descriptor.Descriptor(
  name='FailedMessage',
  full_name='capsule8.api.v0.FailedMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='payload', full_name='capsule8.api.v0.FailedMessage.payload', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error', full_name='capsule8.api.v0.FailedMessage.error', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=247,
  serialized_end=294,
)


_PULLREQUEST = _descriptor.Descriptor(
  name='PullRequest',
  full_name='capsule8.api.v0.PullRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='topic', full_name='capsule8.api.v0.PullRequest.topic', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timeout', full_name='capsule8.api.v0.PullRequest.timeout', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='time', full_name='capsule8.api.v0.PullRequest.time', index=2,
      number=9, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='start_at', full_name='capsule8.api.v0.PullRequest.start_at',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=296,
  serialized_end=397,
)


_PULLRESPONSE = _descriptor.Descriptor(
  name='PullResponse',
  full_name='capsule8.api.v0.PullResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='messages', full_name='capsule8.api.v0.PullResponse.messages', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=399,
  serialized_end=465,
)


_RECEIVEDMESSAGE = _descriptor.Descriptor(
  name='ReceivedMessage',
  full_name='capsule8.api.v0.ReceivedMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ack', full_name='capsule8.api.v0.ReceivedMessage.ack', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='payload', full_name='capsule8.api.v0.ReceivedMessage.payload', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='publish_time_micros', full_name='capsule8.api.v0.ReceivedMessage.publish_time_micros', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='publish_time', full_name='capsule8.api.v0.ReceivedMessage.publish_time', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=467,
  serialized_end=593,
)


_ACKNOWLEDGEREQUEST = _descriptor.Descriptor(
  name='AcknowledgeRequest',
  full_name='capsule8.api.v0.AcknowledgeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='acks', full_name='capsule8.api.v0.AcknowledgeRequest.acks', index=0,
      number=1, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=595,
  serialized_end=629,
)


_ACKNOWLEDGERESPONSE = _descriptor.Descriptor(
  name='AcknowledgeResponse',
  full_name='capsule8.api.v0.AcknowledgeResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='failed_acks', full_name='capsule8.api.v0.AcknowledgeResponse.failed_acks', index=0,
      number=1, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=631,
  serialized_end=673,
)

_PUBLISHRESPONSE.fields_by_name['failed_messages'].message_type = _FAILEDMESSAGE
_PULLREQUEST.fields_by_name['time'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_PULLREQUEST.oneofs_by_name['start_at'].fields.append(
  _PULLREQUEST.fields_by_name['time'])
_PULLREQUEST.fields_by_name['time'].containing_oneof = _PULLREQUEST.oneofs_by_name['start_at']
_PULLRESPONSE.fields_by_name['messages'].message_type = _RECEIVEDMESSAGE
_RECEIVEDMESSAGE.fields_by_name['publish_time'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
DESCRIPTOR.message_types_by_name['PublishRequest'] = _PUBLISHREQUEST
DESCRIPTOR.message_types_by_name['PublishResponse'] = _PUBLISHRESPONSE
DESCRIPTOR.message_types_by_name['FailedMessage'] = _FAILEDMESSAGE
DESCRIPTOR.message_types_by_name['PullRequest'] = _PULLREQUEST
DESCRIPTOR.message_types_by_name['PullResponse'] = _PULLRESPONSE
DESCRIPTOR.message_types_by_name['ReceivedMessage'] = _RECEIVEDMESSAGE
DESCRIPTOR.message_types_by_name['AcknowledgeRequest'] = _ACKNOWLEDGEREQUEST
DESCRIPTOR.message_types_by_name['AcknowledgeResponse'] = _ACKNOWLEDGERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PublishRequest = _reflection.GeneratedProtocolMessageType('PublishRequest', (_message.Message,), dict(
  DESCRIPTOR = _PUBLISHREQUEST,
  __module__ = 'capsule8.api.v0.pubsub_service_pb2'
  # @@protoc_insertion_point(class_scope:capsule8.api.v0.PublishRequest)
  ))
_sym_db.RegisterMessage(PublishRequest)

PublishResponse = _reflection.GeneratedProtocolMessageType('PublishResponse', (_message.Message,), dict(
  DESCRIPTOR = _PUBLISHRESPONSE,
  __module__ = 'capsule8.api.v0.pubsub_service_pb2'
  # @@protoc_insertion_point(class_scope:capsule8.api.v0.PublishResponse)
  ))
_sym_db.RegisterMessage(PublishResponse)

FailedMessage = _reflection.GeneratedProtocolMessageType('FailedMessage', (_message.Message,), dict(
  DESCRIPTOR = _FAILEDMESSAGE,
  __module__ = 'capsule8.api.v0.pubsub_service_pb2'
  # @@protoc_insertion_point(class_scope:capsule8.api.v0.FailedMessage)
  ))
_sym_db.RegisterMessage(FailedMessage)

PullRequest = _reflection.GeneratedProtocolMessageType('PullRequest', (_message.Message,), dict(
  DESCRIPTOR = _PULLREQUEST,
  __module__ = 'capsule8.api.v0.pubsub_service_pb2'
  # @@protoc_insertion_point(class_scope:capsule8.api.v0.PullRequest)
  ))
_sym_db.RegisterMessage(PullRequest)

PullResponse = _reflection.GeneratedProtocolMessageType('PullResponse', (_message.Message,), dict(
  DESCRIPTOR = _PULLRESPONSE,
  __module__ = 'capsule8.api.v0.pubsub_service_pb2'
  # @@protoc_insertion_point(class_scope:capsule8.api.v0.PullResponse)
  ))
_sym_db.RegisterMessage(PullResponse)

ReceivedMessage = _reflection.GeneratedProtocolMessageType('ReceivedMessage', (_message.Message,), dict(
  DESCRIPTOR = _RECEIVEDMESSAGE,
  __module__ = 'capsule8.api.v0.pubsub_service_pb2'
  # @@protoc_insertion_point(class_scope:capsule8.api.v0.ReceivedMessage)
  ))
_sym_db.RegisterMessage(ReceivedMessage)

AcknowledgeRequest = _reflection.GeneratedProtocolMessageType('AcknowledgeRequest', (_message.Message,), dict(
  DESCRIPTOR = _ACKNOWLEDGEREQUEST,
  __module__ = 'capsule8.api.v0.pubsub_service_pb2'
  # @@protoc_insertion_point(class_scope:capsule8.api.v0.AcknowledgeRequest)
  ))
_sym_db.RegisterMessage(AcknowledgeRequest)

AcknowledgeResponse = _reflection.GeneratedProtocolMessageType('AcknowledgeResponse', (_message.Message,), dict(
  DESCRIPTOR = _ACKNOWLEDGERESPONSE,
  __module__ = 'capsule8.api.v0.pubsub_service_pb2'
  # @@protoc_insertion_point(class_scope:capsule8.api.v0.AcknowledgeResponse)
  ))
_sym_db.RegisterMessage(AcknowledgeResponse)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('Z\032github.com/capsule8/api/v0'))

_PUBSUBSERVICE = _descriptor.ServiceDescriptor(
  name='PubsubService',
  full_name='capsule8.api.v0.PubsubService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=676,
  serialized_end=1007,
  methods=[
  _descriptor.MethodDescriptor(
    name='Publish',
    full_name='capsule8.api.v0.PubsubService.Publish',
    index=0,
    containing_service=None,
    input_type=_PUBLISHREQUEST,
    output_type=_PUBLISHRESPONSE,
    options=_descriptor._ParseOptions(descriptor_pb2.MethodOptions(), _b('\202\323\344\223\002\026\"\021/v0/topic/{topic}:\001*')),
  ),
  _descriptor.MethodDescriptor(
    name='Pull',
    full_name='capsule8.api.v0.PubsubService.Pull',
    index=1,
    containing_service=None,
    input_type=_PULLREQUEST,
    output_type=_PULLRESPONSE,
    options=_descriptor._ParseOptions(descriptor_pb2.MethodOptions(), _b('\202\323\344\223\002\023\022\021/v0/topic/{topic}')),
  ),
  _descriptor.MethodDescriptor(
    name='Acknowledge',
    full_name='capsule8.api.v0.PubsubService.Acknowledge',
    index=2,
    containing_service=None,
    input_type=_ACKNOWLEDGEREQUEST,
    output_type=_ACKNOWLEDGERESPONSE,
    options=_descriptor._ParseOptions(descriptor_pb2.MethodOptions(), _b('\202\323\344\223\002\014\"\007/v0/ack:\001*')),
  ),
])
_sym_db.RegisterServiceDescriptor(_PUBSUBSERVICE)

DESCRIPTOR.services_by_name['PubsubService'] = _PUBSUBSERVICE

# @@protoc_insertion_point(module_scope)
