# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: admobilize/mlmodel/v1alpha1/mlmodel_service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from matrix_io.proto.vision.v1 import model_pb2 as matrix__io_dot_vision_dot_v1_dot_model__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='admobilize/mlmodel/v1alpha1/mlmodel_service.proto',
  package='admobilize.mlmodel.v1alpha1',
  syntax='proto3',
  serialized_pb=_b('\n1admobilize/mlmodel/v1alpha1/mlmodel_service.proto\x12\x1b\x61\x64mobilize.mlmodel.v1alpha1\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fmatrix_io/vision/v1/model.proto2\xb4\x02\n\x0eMLModelService\x12\x45\n\x0c\x43reateModels\x12\x1b.matrix_io.vision.v1.Models\x1a\x16.google.protobuf.Empty\"\x00\x12G\n\tGetModels\x12\x1b.matrix_io.vision.v1.Models\x1a\x1b.matrix_io.vision.v1.Models\"\x00\x12K\n\rGetModelsMeta\x12\x1b.matrix_io.vision.v1.Models\x1a\x1b.matrix_io.vision.v1.Models\"\x00\x12\x45\n\x0c\x44\x65leteModels\x12\x1b.matrix_io.vision.v1.Models\x1a\x16.google.protobuf.Empty\"\x00\x42W\n\x1f\x63om.admobilize.mlmodel.v1alpha1B\x0cMLModelProtoP\x01\xa2\x02\x05\x41\x44MML\xaa\x02\x1b\x41\x64Mobilize.MLModel.V1Alpha1b\x06proto3')
  ,
  dependencies=[google_dot_api_dot_annotations__pb2.DESCRIPTOR,google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,matrix__io_dot_vision_dot_v1_dot_model__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\037com.admobilize.mlmodel.v1alpha1B\014MLModelProtoP\001\242\002\005ADMML\252\002\033AdMobilize.MLModel.V1Alpha1'))

_MLMODELSERVICE = _descriptor.ServiceDescriptor(
  name='MLModelService',
  full_name='admobilize.mlmodel.v1alpha1.MLModelService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=175,
  serialized_end=483,
  methods=[
  _descriptor.MethodDescriptor(
    name='CreateModels',
    full_name='admobilize.mlmodel.v1alpha1.MLModelService.CreateModels',
    index=0,
    containing_service=None,
    input_type=matrix__io_dot_vision_dot_v1_dot_model__pb2._MODELS,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetModels',
    full_name='admobilize.mlmodel.v1alpha1.MLModelService.GetModels',
    index=1,
    containing_service=None,
    input_type=matrix__io_dot_vision_dot_v1_dot_model__pb2._MODELS,
    output_type=matrix__io_dot_vision_dot_v1_dot_model__pb2._MODELS,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetModelsMeta',
    full_name='admobilize.mlmodel.v1alpha1.MLModelService.GetModelsMeta',
    index=2,
    containing_service=None,
    input_type=matrix__io_dot_vision_dot_v1_dot_model__pb2._MODELS,
    output_type=matrix__io_dot_vision_dot_v1_dot_model__pb2._MODELS,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='DeleteModels',
    full_name='admobilize.mlmodel.v1alpha1.MLModelService.DeleteModels',
    index=3,
    containing_service=None,
    input_type=matrix__io_dot_vision_dot_v1_dot_model__pb2._MODELS,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MLMODELSERVICE)

DESCRIPTOR.services_by_name['MLModelService'] = _MLMODELSERVICE

# @@protoc_insertion_point(module_scope)
