
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-07-11T16:30:15-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "2c486dc8fc08f5e2a2b023d5657d212d013e4b66",
 "version": "0.5.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
