
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-06-27T21:03:11+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "c99f8b9449511dbc87cf70b572830363057a3773",
 "version": "v1.7.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
