
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-07-03T10:13:24-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "aacf3db7d6a8f11654872e3547d43089419602d8",
 "version": "0.4.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
