# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from goodlens_product.models.base_model_ import Model
from goodlens_product.models.nutrient_item import NutrientItem  # noqa: F401,E501
from goodlens_product.models.nutrient_sub2 import NutrientSub2  # noqa: F401,E501
from goodlens_product import util


class NutrientSub1(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, info: NutrientItem=None, child: List[NutrientSub2]=None):  # noqa: E501
        """NutrientSub1 - a model defined in Swagger

        :param info: The info of this NutrientSub1.  # noqa: E501
        :type info: NutrientItem
        :param child: The child of this NutrientSub1.  # noqa: E501
        :type child: List[NutrientSub2]
        """
        self.swagger_types = {
            'info': NutrientItem,
            'child': List[NutrientSub2]
        }

        self.attribute_map = {
            'info': 'info',
            'child': 'child'
        }

        self._info = info
        self._child = child

    @classmethod
    def from_dict(cls, dikt) -> 'NutrientSub1':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The NutrientSub1 of this NutrientSub1.  # noqa: E501
        :rtype: NutrientSub1
        """
        return util.deserialize_model(dikt, cls)

    @property
    def info(self) -> NutrientItem:
        """Gets the info of this NutrientSub1.


        :return: The info of this NutrientSub1.
        :rtype: NutrientItem
        """
        return self._info

    @info.setter
    def info(self, info: NutrientItem):
        """Sets the info of this NutrientSub1.


        :param info: The info of this NutrientSub1.
        :type info: NutrientItem
        """

        self._info = info

    @property
    def child(self) -> List[NutrientSub2]:
        """Gets the child of this NutrientSub1.


        :return: The child of this NutrientSub1.
        :rtype: List[NutrientSub2]
        """
        return self._child

    @child.setter
    def child(self, child: List[NutrientSub2]):
        """Sets the child of this NutrientSub1.


        :param child: The child of this NutrientSub1.
        :type child: List[NutrientSub2]
        """

        self._child = child
