
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-06-20T22:51:46+0200",
 "dirty": true,
 "error": null,
 "full-revisionid": "bdf12052b101935f32c11cebde6ea26fdd5317b2",
 "version": "0.5.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
