
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-06-25T14:05:00+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "c88b6dc7c9f4b2f31bcdadf22be11de01af6f703",
 "version": "0.0.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
