
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-07-11T09:55:02-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "f29a092b3ba8f2c347be13973e03e5f6432e628e",
 "version": "0.5.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
