# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-06 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_work', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name2',
            field=models.CharField(default='test', max_length=200, verbose_name='Name2'),
            preserve_default=False,
        ),
    ]
