# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-06 20:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_work', '0002_category_name2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name2',
        ),
    ]
