# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-06 23:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_work', '0004_work_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='youtube_id',
            field=models.CharField(default='None', max_length=100, verbose_name='Youtube ID'),
            preserve_default=False,
        ),
    ]
