# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-06 23:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_work', '0005_work_youtube_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='home_page',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
