# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: capsule8/api/v0/config_service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.rpc import status_pb2 as google_dot_rpc_dot_status__pb2
from capsule8.api.v0 import config_pb2 as capsule8_dot_api_dot_v0_dot_config__pb2
from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='capsule8/api/v0/config_service.proto',
  package='capsule8.api.v0',
  syntax='proto3',
  serialized_pb=_b('\n$capsule8/api/v0/config_service.proto\x12\x0f\x63\x61psule8.api.v0\x1a\x17google/rpc/status.proto\x1a\x1c\x63\x61psule8/api/v0/config.proto\x1a\x1cgoogle/api/annotations.proto\">\n\x13\x43reateConfigRequest\x12\'\n\x06\x63onfig\x18\x01 \x01(\x0b\x32\x17.capsule8.api.v0.Config\"9\n\x14\x43reateConfigResponse\x12!\n\x05\x65rror\x18\x01 \x01(\x0b\x32\x12.google.rpc.Status\" \n\x10GetConfigRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"_\n\x11GetConfigResponse\x12\'\n\x06\x63onfig\x18\x01 \x01(\x0b\x32\x17.capsule8.api.v0.Config\x12!\n\x05\x65rror\x18\x02 \x01(\x0b\x32\x12.google.rpc.Status\"\"\n\x12WatchConfigRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"a\n\x13WatchConfigResponse\x12\'\n\x06\x63onfig\x18\x01 \x01(\x0b\x32\x17.capsule8.api.v0.Config\x12!\n\x05\x65rror\x18\x02 \x01(\x0b\x32\x12.google.rpc.Status\"\x14\n\x12ListConfigsRequest\"G\n\x13ListConfigsResponse\x12\r\n\x05names\x18\x01 \x03(\t\x12!\n\x05\x65rror\x18\x02 \x01(\x0b\x32\x12.google.rpc.Status2\xe8\x03\n\rConfigService\x12z\n\x0c\x43reateConfig\x12$.capsule8.api.v0.CreateConfigRequest\x1a%.capsule8.api.v0.CreateConfigResponse\"\x1d\x82\xd3\xe4\x93\x02\x17\"\x12/v0/configs/create:\x01*\x12n\n\tGetConfig\x12!.capsule8.api.v0.GetConfigRequest\x1a\".capsule8.api.v0.GetConfigResponse\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/v0/configs/{name}\x12|\n\x0bWatchConfig\x12#.capsule8.api.v0.WatchConfigRequest\x1a$.capsule8.api.v0.WatchConfigResponse\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/v0/configs/{name}/watch0\x01\x12m\n\x0bListConfigs\x12#.capsule8.api.v0.ListConfigsRequest\x1a$.capsule8.api.v0.ListConfigsResponse\"\x13\x82\xd3\xe4\x93\x02\r\x12\x0b/v0/configsB\x1cZ\x1agithub.com/capsule8/api/v0b\x06proto3')
  ,
  dependencies=[google_dot_rpc_dot_status__pb2.DESCRIPTOR,capsule8_dot_api_dot_v0_dot_config__pb2.DESCRIPTOR,google_dot_api_dot_annotations__pb2.DESCRIPTOR,])




_CREATECONFIGREQUEST = _descriptor.Descriptor(
  name='CreateConfigRequest',
  full_name='capsule8.api.v0.CreateConfigRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='config', full_name='capsule8.api.v0.CreateConfigRequest.config', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=142,
  serialized_end=204,
)


_CREATECONFIGRESPONSE = _descriptor.Descriptor(
  name='CreateConfigResponse',
  full_name='capsule8.api.v0.CreateConfigResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='error', full_name='capsule8.api.v0.CreateConfigResponse.error', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=206,
  serialized_end=263,
)


_GETCONFIGREQUEST = _descriptor.Descriptor(
  name='GetConfigRequest',
  full_name='capsule8.api.v0.GetConfigRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='capsule8.api.v0.GetConfigRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=265,
  serialized_end=297,
)


_GETCONFIGRESPONSE = _descriptor.Descriptor(
  name='GetConfigResponse',
  full_name='capsule8.api.v0.GetConfigResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='config', full_name='capsule8.api.v0.GetConfigResponse.config', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error', full_name='capsule8.api.v0.GetConfigResponse.error', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=299,
  serialized_end=394,
)


_WATCHCONFIGREQUEST = _descriptor.Descriptor(
  name='WatchConfigRequest',
  full_name='capsule8.api.v0.WatchConfigRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='capsule8.api.v0.WatchConfigRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=396,
  serialized_end=430,
)


_WATCHCONFIGRESPONSE = _descriptor.Descriptor(
  name='WatchConfigResponse',
  full_name='capsule8.api.v0.WatchConfigResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='config', full_name='capsule8.api.v0.WatchConfigResponse.config', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error', full_name='capsule8.api.v0.WatchConfigResponse.error', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=432,
  serialized_end=529,
)


_LISTCONFIGSREQUEST = _descriptor.Descriptor(
  name='ListConfigsRequest',
  full_name='capsule8.api.v0.ListConfigsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=531,
  serialized_end=551,
)


_LISTCONFIGSRESPONSE = _descriptor.Descriptor(
  name='ListConfigsResponse',
  full_name='capsule8.api.v0.ListConfigsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='names', full_name='capsule8.api.v0.ListConfigsResponse.names', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error', full_name='capsule8.api.v0.ListConfigsResponse.error', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=553,
  serialized_end=624,
)

_CREATECONFIGREQUEST.fields_by_name['config'].message_type = capsule8_dot_api_dot_v0_dot_config__pb2._CONFIG
_CREATECONFIGRESPONSE.fields_by_name['error'].message_type = google_dot_rpc_dot_status__pb2._STATUS
_GETCONFIGRESPONSE.fields_by_name['config'].message_type = capsule8_dot_api_dot_v0_dot_config__pb2._CONFIG
_GETCONFIGRESPONSE.fields_by_name['error'].message_type = google_dot_rpc_dot_status__pb2._STATUS
_WATCHCONFIGRESPONSE.fields_by_name['config'].message_type = capsule8_dot_api_dot_v0_dot_config__pb2._CONFIG
_WATCHCONFIGRESPONSE.fields_by_name['error'].message_type = google_dot_rpc_dot_status__pb2._STATUS
_LISTCONFIGSRESPONSE.fields_by_name['error'].message_type = google_dot_rpc_dot_status__pb2._STATUS
DESCRIPTOR.message_types_by_name['CreateConfigRequest'] = _CREATECONFIGREQUEST
DESCRIPTOR.message_types_by_name['CreateConfigResponse'] = _CREATECONFIGRESPONSE
DESCRIPTOR.message_types_by_name['GetConfigRequest'] = _GETCONFIGREQUEST
DESCRIPTOR.message_types_by_name['GetConfigResponse'] = _GETCONFIGRESPONSE
DESCRIPTOR.message_types_by_name['WatchConfigRequest'] = _WATCHCONFIGREQUEST
DESCRIPTOR.message_types_by_name['WatchConfigResponse'] = _WATCHCONFIGRESPONSE
DESCRIPTOR.message_types_by_name['ListConfigsRequest'] = _LISTCONFIGSREQUEST
DESCRIPTOR.message_types_by_name['ListConfigsResponse'] = _LISTCONFIGSRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CreateConfigRequest = _reflection.GeneratedProtocolMessageType('CreateConfigRequest', (_message.Message,), dict(
  DESCRIPTOR = _CREATECONFIGREQUEST,
  __module__ = 'capsule8.api.v0.config_service_pb2'
  # @@protoc_insertion_point(class_scope:capsule8.api.v0.CreateConfigRequest)
  ))
_sym_db.RegisterMessage(CreateConfigRequest)

CreateConfigResponse = _reflection.GeneratedProtocolMessageType('CreateConfigResponse', (_message.Message,), dict(
  DESCRIPTOR = _CREATECONFIGRESPONSE,
  __module__ = 'capsule8.api.v0.config_service_pb2'
  # @@protoc_insertion_point(class_scope:capsule8.api.v0.CreateConfigResponse)
  ))
_sym_db.RegisterMessage(CreateConfigResponse)

GetConfigRequest = _reflection.GeneratedProtocolMessageType('GetConfigRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETCONFIGREQUEST,
  __module__ = 'capsule8.api.v0.config_service_pb2'
  # @@protoc_insertion_point(class_scope:capsule8.api.v0.GetConfigRequest)
  ))
_sym_db.RegisterMessage(GetConfigRequest)

GetConfigResponse = _reflection.GeneratedProtocolMessageType('GetConfigResponse', (_message.Message,), dict(
  DESCRIPTOR = _GETCONFIGRESPONSE,
  __module__ = 'capsule8.api.v0.config_service_pb2'
  # @@protoc_insertion_point(class_scope:capsule8.api.v0.GetConfigResponse)
  ))
_sym_db.RegisterMessage(GetConfigResponse)

WatchConfigRequest = _reflection.GeneratedProtocolMessageType('WatchConfigRequest', (_message.Message,), dict(
  DESCRIPTOR = _WATCHCONFIGREQUEST,
  __module__ = 'capsule8.api.v0.config_service_pb2'
  # @@protoc_insertion_point(class_scope:capsule8.api.v0.WatchConfigRequest)
  ))
_sym_db.RegisterMessage(WatchConfigRequest)

WatchConfigResponse = _reflection.GeneratedProtocolMessageType('WatchConfigResponse', (_message.Message,), dict(
  DESCRIPTOR = _WATCHCONFIGRESPONSE,
  __module__ = 'capsule8.api.v0.config_service_pb2'
  # @@protoc_insertion_point(class_scope:capsule8.api.v0.WatchConfigResponse)
  ))
_sym_db.RegisterMessage(WatchConfigResponse)

ListConfigsRequest = _reflection.GeneratedProtocolMessageType('ListConfigsRequest', (_message.Message,), dict(
  DESCRIPTOR = _LISTCONFIGSREQUEST,
  __module__ = 'capsule8.api.v0.config_service_pb2'
  # @@protoc_insertion_point(class_scope:capsule8.api.v0.ListConfigsRequest)
  ))
_sym_db.RegisterMessage(ListConfigsRequest)

ListConfigsResponse = _reflection.GeneratedProtocolMessageType('ListConfigsResponse', (_message.Message,), dict(
  DESCRIPTOR = _LISTCONFIGSRESPONSE,
  __module__ = 'capsule8.api.v0.config_service_pb2'
  # @@protoc_insertion_point(class_scope:capsule8.api.v0.ListConfigsResponse)
  ))
_sym_db.RegisterMessage(ListConfigsResponse)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('Z\032github.com/capsule8/api/v0'))

_CONFIGSERVICE = _descriptor.ServiceDescriptor(
  name='ConfigService',
  full_name='capsule8.api.v0.ConfigService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=627,
  serialized_end=1115,
  methods=[
  _descriptor.MethodDescriptor(
    name='CreateConfig',
    full_name='capsule8.api.v0.ConfigService.CreateConfig',
    index=0,
    containing_service=None,
    input_type=_CREATECONFIGREQUEST,
    output_type=_CREATECONFIGRESPONSE,
    options=_descriptor._ParseOptions(descriptor_pb2.MethodOptions(), _b('\202\323\344\223\002\027\"\022/v0/configs/create:\001*')),
  ),
  _descriptor.MethodDescriptor(
    name='GetConfig',
    full_name='capsule8.api.v0.ConfigService.GetConfig',
    index=1,
    containing_service=None,
    input_type=_GETCONFIGREQUEST,
    output_type=_GETCONFIGRESPONSE,
    options=_descriptor._ParseOptions(descriptor_pb2.MethodOptions(), _b('\202\323\344\223\002\024\022\022/v0/configs/{name}')),
  ),
  _descriptor.MethodDescriptor(
    name='WatchConfig',
    full_name='capsule8.api.v0.ConfigService.WatchConfig',
    index=2,
    containing_service=None,
    input_type=_WATCHCONFIGREQUEST,
    output_type=_WATCHCONFIGRESPONSE,
    options=_descriptor._ParseOptions(descriptor_pb2.MethodOptions(), _b('\202\323\344\223\002\032\022\030/v0/configs/{name}/watch')),
  ),
  _descriptor.MethodDescriptor(
    name='ListConfigs',
    full_name='capsule8.api.v0.ConfigService.ListConfigs',
    index=3,
    containing_service=None,
    input_type=_LISTCONFIGSREQUEST,
    output_type=_LISTCONFIGSRESPONSE,
    options=_descriptor._ParseOptions(descriptor_pb2.MethodOptions(), _b('\202\323\344\223\002\r\022\013/v0/configs')),
  ),
])
_sym_db.RegisterServiceDescriptor(_CONFIGSERVICE)

DESCRIPTOR.services_by_name['ConfigService'] = _CONFIGSERVICE

# @@protoc_insertion_point(module_scope)
