
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "b5f75c6935978888245964893d415e94be8ee657",
 "version": "1969"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
