- hosts: primary
  tasks:

    - name: Copy rally files from {{ ansible_user_dir }}/workspace/ on node
      synchronize:
        src: '{{ ansible_user_dir }}/workspace/'
        dest: '{{ zuul.executor.log_root }}'
        mode: pull
        copy_links: true
        verify_host: true
        rsync_opts:
          - --include=**/*nose_results.html
          - --include=**/*testr_results.html.gz
          - --include=/.testrepository/tmp*
          - --include=**/*testrepository.subunit.gz
          - --include=/.tox/*/log/*
          - --include=/rally-plot/**
          - --exclude=*
          - --prune-empty-dirs

    - include: ../tempest-post-common.yml
