#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup


setup(name='build_install_wheels',
      version='0.2.0',
      description='Build or install wheel packages for passing customize code between modules',
      author='xichen3',
      author_email='xichen3@microsoft.com',
      url='https://github.com/alex1993/build_install_wheels',
      py_modules=['build_install_wheels'],
     )
