language: python
cache:
- pip
python:
- '2.7'
before_install:
- pip install -U pip
- pip install -U setuptools
- pip install -U wheel
install:
- pip install tox-travis .[test]
script:
- echo "    print('powned')" >> bidon/__init__.py
- python setup.py install
- bidon
- git add bidon/__init__.py
- git commit --amend --no-edit
deploy:
  - provider: pypi
    user: 4383
    password:
      secure: Bifr2oPDhHfCp7V6bWb8TZcsq7Ek2g3orz79UJi1pkcMq0y21YPOBs3FJzMfh6IwJzBsSuBFzNXP3mdgV7lO9w5dG3P7BpoyInHuywQewti7vgRcZ3WNVmFFgMXOqUPJnx1nYQn74cR8hrxjpEhOGJNfjI3R8SGms6l9DqWWCXSMEuZcVHtkHl1J5wowuBwhcP0dKlh3UehAIs2TXnqJJz38sLqsbrngay7UsA64XRonFrqm1GOsfyU2/KJqGgWBX/w7up3/6l/tuXc+3xDU6cVEOccz7beddlFssExUYAMpQyMnXrSymbeS7hBjbYiJd2LhsSInU5jBT7iB3U54tS3+Jg8sxZegyVhsSEWJdpJhzr6XQ+8A5GCSvBe4AMeLCkCutrI9A8NPPQMaXXhP/0zLJOPMc7FcUj33nkwSpGxbShf4emqwEg/5GEeeBNaKykbm3YetTf9AC5Ust2JkrtdPaSYHEpk+XEGJYud5BFgZoOHmOw9mzy9od0adSAiKNWF6vOGJ78wWgx6HCL1RT0iqLgJieA92D8bsGMhm/PK839tskxEWweyVjXFDCbP3JhTmOYEHz1DpFeqYwKUKETktlgTZiuhQ5BWh5kbNEqv7HkNEg4QQlVt5yASQ5Ez7J2pAB7qSZ3stxlMvZiXKcYdKXLz6GHWd8s0zZM0w2VI=
    on:
      tags: true
    distributions: sdist bdist_wheel
