
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-06-21T09:28:07+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "71112e0972ea4427d84e881344577b59e9ad39e6",
 "version": "3.0.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
