protocol:
  telnet:
    first_prompt_timeout: 20
    esc_char_timeout: 20
    connect_timeout: 180

  ssh:
    # Wait until first prompt comes up
    first_prompt_timeout: 30
    # SSH -o ConnectTimeout value (30) - not supported on SunOS
    connect_timeout: 120
    options:
      - "UserKnownHostsFile=/dev/null"
      - "StrictHostKeyChecking=no"
      - "LogLevel=ERROR"

  console:
    first_prompt_timeout: 20
    esc_char_timeout: 20
    connect_timeout: 180


driver:
  eXR:
    # Wait for the term len when executing admin/calvados mode commands. This is required to determine
    # whether the 'admin' command was sent or 'admin .....' where the output of the command must be captured.
    calvados_term_wait_time: 2
    planes:
      admin: "admin"

  XR:
    planes:
      admin: "admin"
      qnx: "run"
