language: en
prefixes:
  a: 'http://www.w3.org/1999/02/22-rdf-syntax-ns#type'
  owl: 'http://www.w3.org/2002/07/owl#'
  rdf: 'http://www.w3.org/1999/02/22-rdf-syntax-ns#'
  rdfs: 'http://www.w3.org/2000/01/rdf-schema#'
  xml: 'http://www.w3.org/XML/1998/namespace#'
  xsd: 'http://www.w3.org/2001/XMLSchema#'
  nfo: 'http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#'
  dbo: 'http://dbpedia.org/ontology/'
  dbop: 'http://dbpedia.org/page/'
  mov: 'http://www.movieontology.org/2009/10/01/movieontology.owl#'
  geo: 'http://www.w3.org/2003/01/geo/wgs84_pos#'

agents:
  movies:
    - mov:Movie
    - mov:TVShow

  music:
    - nfo:Audio
