language: python
python:
    - "3.6"
install:
    - pip install pipenv
    - pipenv install --dev
script:
    - pipenv run test
after_success:
    - pipenv run codecov
notifications:
    email: false
