language: python
python:
  - 3.5
install:
  - sudo apt-get install graphviz asciidoc pandoc
  - pip install -r requirements.txt
script:
  - python ./bin/validate.py
  - cd docs && make html && cd ..
after_success:
  - ./bin/deploy
