# coding: utf-8

"""
    BIMData API

    BIMData API documentation  # noqa: E501

    OpenAPI spec version: v1
    Contact: contact@bimdata.io
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import bimdata_api_client
from bimdata_api_client.models.bim_snippet import BimSnippet  # noqa: E501
from bimdata_api_client.rest import ApiException


class TestBimSnippet(unittest.TestCase):
    """BimSnippet unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBimSnippet(self):
        """Test BimSnippet"""
        # FIXME: construct object with mandatory attributes with example values
        # model = bimdata_api_client.models.bim_snippet.BimSnippet()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
