
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-07-06T15:42:50-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "40608a881f149698622ec594e8bd15035580b271",
 "version": "2.1.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
