
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-07-06T14:25:26+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "14787a6466943d61184f24c0dbe78136f77bbbc5",
 "version": "v0.4.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
