# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-07-06 13:20
from __future__ import unicode_literals

from django.db import migrations

from django_pathman.helpers import read_sql

FORWARDS_SQL = read_sql('alter_child_index_v1.sql')
REVERSE_SQL = 'DROP FUNCTION alter_child_index(parent_table text, itable text, is_debug boolean);'


class Migration(migrations.Migration):

    dependencies = [

    ]

    operations = [
        migrations.RunSQL(sql=FORWARDS_SQL, reverse_sql=REVERSE_SQL)
    ]