# Autogenerated by Astropy-affiliated package astropy_helpers's setup.py on 2018-02-28 16:59:15.016632
from __future__ import unicode_literals
import datetime

version = "2.0"
githash = "ed2e7897862ae9e979b336df670d7a5541cdd8f0"


major = 2
minor = 0
bugfix = 0

release = True
timestamp = datetime.datetime(2018, 2, 28, 16, 59, 15, 16632)
debug = False

try:
    from ._compiler import compiler
except ImportError:
    compiler = "unknown"

try:
    from .cython_version import cython_version
except ImportError:
    cython_version = "unknown"
