
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-07-02T14:30:53+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "de6836731308e690ea9b6e6629c612bcbcd81f35",
 "version": "18.0.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
