
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-06-29T14:33:04-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "cf0342f78882622f9179f6f2d6a173f9abcf37d3",
 "version": "1.0.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
