application: lame
version_arg: --version
inout_args: --brief {infile} {outfile}.mp3

combinations:

  # Speech
  speech, simple, mono:      -T -q0 -b8 -V8.0 --lowpass 13000 -mm
  speech, moderate, mono:    -T -q0 -b8 -V7.5 --lowpass 14000 -mm
  speech, complex, mono:     -T -q0 -b8 -V7.3 --lowpass 15000 -mm
  speech, simple, stereo:    -T -q0 -b8 -V7.0 --lowpass 13000
  speech, moderate, stereo:  -T -q0 -b8 -V6.7 --lowpass 15000
  speech, complex, stereo:   -T -q0 -b8 -V6.5 --lowpass 16000

  # Music
  music, simple, mono:       -T -q0 -b8 -V7.0 -mm
  music, moderate, mono:     -T -q0 -b8 -V6.5 -mm
  music, complex, mono:      -T -q0 -b8 -V6.0 -mm
  music, simple, stereo:     -T -q0 -b8 -V5.5
  music, moderate, stereo:   -T -q0 -b8 -V4.5
  music, complex, stereo:    -T -q0 -b8 -V3.5

  # Mixed
  mixed, simple, mono:       -T -q0 -b8 -V7.2 -mm
  mixed, moderate, mono:     -T -q0 -b8 -V6.7 -mm
  mixed, complex, mono:      -T -q0 -b8 -V6.3 -mm
  mixed, simple, stereo:     -T -q0 -b8 -V6.0
  mixed, moderate, stereo:   -T -q0 -b8 -V5.3
  mixed, complex, stereo:    -T -q0 -b8 -V4.5

  # Effects
  effects, simple, mono:     -T -q0 -b8 -V7.2 -mm
  effects, moderate, mono:   -T -q0 -b8 -V7.0 -mm
  effects, complex, mono:    -T -q0 -b8 -V6.7 -mm
  effects, simple, stereo:   -T -q0 -b8 -V6.5
  effects, moderate, stereo: -T -q0 -b8 -V6.0
  effects, complex, stereo:  -T -q0 -b8 -V5.0

  # Filler
  filler, simple, mono:      -T -q0 -b4 -mm
  filler, moderate, mono:    -T -q0 -b4 -mm
  filler, complex, mono:     -T -q0 -b4 -mm
  filler, simple, stereo:    -T -q0 -b4 -mm
  filler, moderate, stereo:  -T -q0 -b4 -mm
  filler, complex, stereo:   -T -q0 -b4 -mm
