# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 12:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pyscada', '0034_auto_20170213_0855'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jofra350Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(default=b'127.0.0.1')),
                ('port', models.PositiveSmallIntegerField(default=17001)),
                ('jofra350_device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pyscada.Device')),
            ],
        ),
        migrations.CreateModel(
            name='Jofra350Variable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_type', models.CharField(choices=[(b'INT_RTD', b'Internal Reference Sensor')], default=b'', max_length=10)),
                ('field_type', models.CharField(choices=[(b'INT_RTD', b'Internal Reference Sensor')], default=b'', max_length=10)),
                ('jofra350_variable', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pyscada.Variable')),
            ],
        ),
    ]
