# One endpoint settings
one:
  name: One
  host: https://raw.githubusercontent.com/tadashi-aikawa/jumeaux-toolbox/master/vagrant/ignore_properties/one

# The other endpoint settings
other:
  name: Other
  host: https://raw.githubusercontent.com/tadashi-aikawa/jumeaux-toolbox/master/vagrant/ignore_properties/other

# Output path for API responses
output:
  response_dir: responses

# Add-ons to use. See https://tadashi-aikawa.github.io/jumeaux/ja/addons
addons:
  log2reqs:
    name: plain

  res2dict:
    - name: json
      config:
        # Usually, we don't need to set `mime_types`
        # In this case, `raw.githubusercontent.com` always return `mime-type: text/plain` even if response is json.
        # So we need to specify `mime_types` as following now.
        mime_types: [text/plain]

  judgement:
    # Ignore specific properties.
    # Ex. uniq id per request, request time, ...etc
    - name: ignore_properties
      config:
        ignores:
          - title: Ignore ignored_id
            conditions:
              - changed:
                  - root<'ignored_id'>
          - title: Ignore favorite only if path includes `/same`
            conditions:
              - path: .*/same.*
                added: [root<'members'><\d+><'favorite'>.*]
                changed: [root<'members'><\d+><'favorite'>.*]
                removed: [root<'members'><\d+><'favorite'>.*]

  store_criterion:
    # Store different responses
    - name: general
      config:
        statuses:
          - different

  did_challenge:
    # Sleep 0.5 sec between challenges
    - name: sleep
      config:
        min: 0.5
        max: 0.5

  dump:
    - name: json
      config:
        # Usually, we don't need to set `mime_types`
        # In this case, `raw.githubusercontent.com` always return `mime-type: text/plain` even if response is json.
        # So we need to specify `mime_types` as following now.
        mime_types: [text/plain]

#  final:
#    # Send results to aws for check by Miroir
#    - name: miroir
#      config:
#        table: miroir
#        bucket: mamansoft-miroir
#        cache_max_age: 3600
