
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-06-27T13:25:37-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "dc6a88fa317f90b2e0e9d3d1c161a23e668bccaf",
 "version": "5.0.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
