
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-06-18T11:05:29-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "0067f6fd6a04ad6e88dcc18988f882417d4b20a9",
 "version": "0.0.21"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
