
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-06-21T23:51:26+0200",
 "dirty": true,
 "error": null,
 "full-revisionid": "c2316946994f75675483cb78b56cc74393baebec",
 "version": "2.4.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
