
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-06-17T13:25:31-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "d44c76840a88d084f50435d95a812685ed9390e8",
 "version": "0.9.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
