[build-system]
requires = ["flit"]
build-backend = "flit.buildapi"

[tool.flit.metadata]
module = "flit_callable"
author = "xichen3"
author-email = "xichen3@microsoft.com"
home-page = "https://www.github.com"
classifiers = ["License :: OSI Approved :: MIT License"]

