# coding: utf-8

"""
    BIMData API

    BIMData API documentation  # noqa: E501

    OpenAPI spec version: v1
    Contact: contact@bimdata.io
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class ProjectAction(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'project_action': 'str'
    }

    attribute_map = {
        'project_action': 'project_action'
    }

    def __init__(self, project_action=None):  # noqa: E501
        """ProjectAction - a model defined in OpenAPI"""  # noqa: E501

        self._project_action = None
        self.discriminator = None

        if project_action is not None:
            self.project_action = project_action

    @property
    def project_action(self):
        """Gets the project_action of this ProjectAction.  # noqa: E501


        :return: The project_action of this ProjectAction.  # noqa: E501
        :rtype: str
        """
        return self._project_action

    @project_action.setter
    def project_action(self, project_action):
        """Sets the project_action of this ProjectAction.


        :param project_action: The project_action of this ProjectAction.  # noqa: E501
        :type: str
        """
        allowed_values = ["update", "createTopic", "createDocument", "updateProjectExtensions"]  # noqa: E501
        if project_action not in allowed_values:
            raise ValueError(
                "Invalid value for `project_action` ({0}), must be one of {1}"  # noqa: E501
                .format(project_action, allowed_values)
            )

        self._project_action = project_action

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ProjectAction):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
