# Generated by Django 2.0.5 on 2018-06-15 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomVariant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PollUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=64)),
                ('username', models.CharField(max_length=32, null=True)),
                ('first_name', models.TextField()),
                ('last_name', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('image', models.ImageField(upload_to='')),
                ('description', models.TextField(max_length=255)),
                ('weight', models.PositiveIntegerField(default=0)),
                ('votes', models.ManyToManyField(blank=True, to='telebaka_lprmerch_poll.PollUser')),
            ],
            options={
                'ordering': ['weight'],
            },
        ),
        migrations.AddField(
            model_name='customvariant',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='telebaka_lprmerch_poll.PollUser'),
        ),
    ]
