# Generated by Django 2.0.5 on 2018-06-15 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telebaka_lprmerch_poll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='polluser',
            name='accepting_custom',
            field=models.BooleanField(default=False),
        ),
    ]
