"""
Since many function take the same parameters, these constants are used to standardize the help texts.
"""
CONFIG_FILE = "Persistent configuration file path."
PASSWORD = "Set a password to ensure your keys are not stored unencrypted."
VERBOSE = "Verbosity level, for logging etc."
NETWORK = "Network you wish to set."
SETTING = "Setting name + value you wish to specifically set."
SHOW_SECRET = "Show the passphrases."
COVER_FEES = "Cover the fees of each payout transaction."
MAX_WEIGHT = "Maximum allowed voter balance."
SHARE = "Percentage the voters receive (95 means the delegate keep 5%)"
STORE = "Store the current pending balances of the voters in the DB."
PRINT = "Print the current pending balances of the voters."
MESSAGE = "Message to send to voters in the vendorField"
MIN_SHARE = "Minimum built up balance each voter needs before being paid."
COVERED_FEES = "Were payout fees covered during the previous payment runs? (in between delegate reward payouts)"
SHARED_PERCENTAGE = "Shared percentage used during the previous runs (in between delegate reward payouts)"
REWARDS_WALLET = "Wallet where rewards payments are sent"
TIP = "Send a tip to Charles for developing this CLI and maintaining it."