
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-07-13T15:26:26+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "135ddc3cae480247b812194adda74fe51cd74794",
 "version": "0.4a13"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
