---
rules:
  default:
    merge_strategy:
      method: rebase
      rebase_fallback: none
    protection:
      required_pull_request_reviews: null
      required_status_checks:
        strict: true
        contexts:
          - 'continuous-integration/travis-ci/pr'
          - 'mergify/allow'
          - 'LGTM analysis: Python'
      enforce_admins: true
