[tool.poetry]
name = "aioacm-sdk-python"
version = "0.3.13"
description = "Python client for ACM with asyncio support."
authors = ["songww <sww4718168@gmail.com>"]
license = "Apache-2.0"
repository = "https://github.com/ioimop/aioacm"
packages = [
    { include = "aioacm" }
]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.5"
aiohttp = "^3.3"
aliyun-python-sdk-core-v3 = {version="^2.8", optional=true}
aliyun-python-sdk-kms = {version="^2.5", optional=true}

[tool.poetry.dev-dependencies]
pytest = "^3.5"
pytest-asyncio = "^0.8.0"
