# Edit bigswitch-config.yaml file. Change BCF controller IP and the credentials.

resource_registry:
  OS::TripleO::ControllerExtraConfigPre: /usr/share/openstack-tripleo-heat-templates/puppet/extraconfig/pre_deploy/controller/neutron-ml2-bigswitch.yaml
  OS::TripleO::ComputeExtraConfigPre: /usr/share/openstack-tripleo-heat-templates/puppet/extraconfig/pre_deploy/compute/neutron-ml2-bigswitch.yaml

parameter_defaults:
  ControllerExtraConfig:
    neutron::agents::bigswitch::lldp_enabled: true
    neutron::agents::dhcp::enable_force_metadata: true
    neutron::agents::dhcp::enable_isolated_metadata: true
    neutron::agents::dhcp::enable_metadata_network: false
    neutron::server::l3_ha: false
  NeutronMechanismDrivers: openvswitch,bsn_ml2
  KeystoneNotificationDriver: messaging

  NovaComputeExtraConfig:
    neutron::agents::bigswitch::lldp_enabled: true

  NeutronBigswitchRestproxyServers: <Update-this-value>
  NeutronBigswitchRestproxyServerAuth: <Update-this-value>
  NeutronBigswitchRestproxyAutoSyncOnFailure: True
  NeutronBigswitchRestproxyConsistencyInterval: 10
  NeutronBigswitchRestproxyNeutronId: <Update-this-value> # <<< Name used to prefix the tenant/project name on BCF.
  NeutronBigswitchRestproxyServerSsl: True
  NeutronBigswitchRestproxySslCertDirectory: /var/lib/neutron
