language: python
sudo: false

cache:
  pip: true

matrix:
    include:
        - python: "2.7"
          env: TOXENV=lint-py2
        - python: "3.6"
          env: TOXENV=lint-py3
        - python: "2.7"
          env: TOXENV=py27
        - python: "3.4"
          env: TOXENV=py34
        - python: "3.5"
          env: TOXENV=py35
        - python: "3.6"
          env: TOXENV=py36

install:
    - travis_retry pip install -U -c constraints.txt tox coveralls coverage

script:
    - travis_retry tox

after_success:
    - coverage combine
    - coveralls
