language: python

# for container-y goodness:
sudo: false

env:
  secure: "r9ZM4KOnCohwd5xiXOCC4iTNWCrVJpEyN1wMPpaJTVentTnUs1pABw7CUgic0kYWbjC5BWh3kQBsXb1uQrxkwNWfBqmCuhBxSlxdd5mwVjF+jwnwq4R16pJ59l2NPThKirGw5xodLK/Sd5jw9eejToXx6Ak6ZHMzFan3A7DqmzXttx5mqmjmNujFIYRT19B7u6T06/cOWAOypajKJp2npHx5c2AXrd5+HdD4qfYwUBI1Rtj1GEKcQvDivOSOps3lXgr0Pwm6dH1VDegpvzlzcZ4KSVo6rvM7eImDuzgwloZlOuolqN7MCpKdTildnsYnTfErltb1oJlYkkkG0zMUMjA73owSTmXXpRoXfJpXuoxW8xwjG3K94uLRCB/ujFt/myHfUwJBw/OvnFOI2TAaS+B6MXgISjBNS6NXyJU+iM7K3zjOtzPO08yYy1he8gtX7sQ4k8wB0hPRImbbD9pPww7Oh6+vGyyTcGauy5R55fP2ZP0pj6VHAVqavQfRcUKxrcQ8fQBqV201wKgZJQgHe41+5K2NQlHV2toh32D3mzoT+GdRovSFnhJk/V3jXdblN7h2oEjVa7EGogwlbXtNoS3gikar9IVrw88wXuHwjujG7uB2yzBYiXG6tE2UJoliRXx0q0yImSnX2cWUXxIbuDvlj0U4FYYFNnY1BYU6N3Y="

python:
  - "2.7"
  - "3.6"

install:
  - "pip install --upgrade pip setuptools"
  - "pip install -Ue .[test]"

script: coverage run --source coveralls_check,tests -m py.test tests.py

after_success:
  - "COVERALLS_PARALLEL=true coveralls"

jobs:
  include:

    - stage: coverage
      python: 3.6
      after_success: skip

      # woof woof!
      install: "pip install -Ue ."
      script: "coveralls-check $TRAVIS_COMMIT --parallel-build-number $TRAVIS_BUILD_NUMBER --repo-token $COVERALLS_REPO_TOKEN"

    - stage: release
      if: tag IS present
      python: 3.6
      script: skip
      # work around https://github.com/travis-ci/travis-ci/issues/8337:
      after_success: true

      install: "pip install -Ue .[build]"
      deploy:
        provider: pypi
        user: chrisw
        password:
          secure: AGZi6g+W0meTWg0nc+J1bzpYbSmfTaBl4t713M56U4auwAfaKuh8kBwfQksz1yfBsvUETBcg9WQPRvqIdj0nrfAIPVpZ28I6TtJhg9zh/B/jZUerhqSB8+4W6qRIMWxspg0NftLIpoJYVC+rpqDwweJ7+LJbcYUyAIG66HLUd344el8t6UDD/CqzdFERfRH13EaG8rJAMPlpiFWp6V/TVPGVkkgEc2+geiDm5Quk/ziEaoLgElHWufHBCf8It3F+ZyZLLKPJ1KzCo7P10JypV1TNVa8JtsicVhbJwbx72vkirPhtRtTyzZGvZ20CDTijfA62E1FTAQ1/Myd4h9W6zaikQ+/VsZYcMZTZzsPsMRLxYNdDbwWzG3JOeZouFIIT8/4nBmlZGv3ioTMDKhO/mb5wS80wTaoozVguRUpf0PON6vTUhRzYLTjpw6R4ZljQzZ2Unh+yZRyF6RMmviWJlYfk3byMHurIe9qRq5Ykfc7uwNPLW7fPXPgpEyUMZUSj0bIXZj8vNt/lE6Qzsoa5sYK1d1fC6XUps8rTrV62BmruIs4C4w1mcEPwIM9ucJswkx8do8mPRMBTjpq1+aPvKgyy2Ovpg3zazNZohAYqrBNyaYxESaYcw9dYUpsi9+813UecbLNtcFDU8AdaEV9rk61SljQWQp9t2NXctRReL1Q=
        on:
          tags: true
          repo: cjw296/coveralls-check
          python: "3.6"
        skip_cleanup: true
        distributions: "sdist bdist_wheel"
