
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-06-28T11:57:35-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "657e94f964d3f299fcc3946cefe049f05a02795f",
 "version": "0.2.1-beta"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
