[tool.poetry]
name = "wint"
version = "0.1.0"
description = "Dependency injection with type hints"
authors = ["Stanislav Lobanov <n10101010@gmail.com>"]

license = "MIT"

readme = 'README.md'
repository = "https://github.com/asyncee/wint"
homepage = "https://github.com/asyncee/wint"
documentation = "https://github.com/asyncee/wint"

keywords = ['dependency injection', 'type hinting', 'wint']

include = ["wint/punq/*"]

[tool.poetry.dependencies]
python = ">=3.6"

[tool.poetry.dev-dependencies]
pytest = "^3.0"
