# Generated by Django 2.0.7 on 2018-07-13 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_organization_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'permissions': (('view_organization', 'View organization'),)},
        ),
    ]
