
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-06-16T17:39:38+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "33f7d0e2fa2df429bb0fc15c64e18756e6b53268",
 "version": "1.4.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
