language: python
python:
  - '3.5'
  - '3.6'
install:
  - pip install tox
script:
  - tox
jobs:
  include:
    - stage: deploy
      python: '3.6'
      install: skip
      script: skip
      deploy:

      - provider: pypi
        skip_existing: true
        user: $PYPI_USER
        password: $PYPI_PASSWORD
        on:
          all_branches: true
