
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-07-11T12:02:47-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "38363356c10b99877ee49676126d0c2af653827d",
 "version": "0.0.0a3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
