# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mw_mrsprint.ui'
#
# Created by: pyqtgraph.Qt UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from pyqtgraph.Qt import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1002, 1352)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/mrsprint/MRSprintIcon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAutoFillBackground(True)
        MainWindow.setIconSize(QtCore.QSize(42, 42))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_4 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.toolBarSampleElement = QtGui.QToolBar(MainWindow)
        self.toolBarSampleElement.setEnabled(True)
        self.toolBarSampleElement.setStyleSheet(_fromUtf8(""))
        self.toolBarSampleElement.setIconSize(QtCore.QSize(42, 42))
        self.toolBarSampleElement.setObjectName(_fromUtf8("toolBarSampleElement"))
        MainWindow.addToolBar(QtCore.Qt.LeftToolBarArea, self.toolBarSampleElement)
        self.toolBar2DEditor = QtGui.QToolBar(MainWindow)
        self.toolBar2DEditor.setIconSize(QtCore.QSize(32, 32))
        self.toolBar2DEditor.setObjectName(_fromUtf8("toolBar2DEditor"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar2DEditor)
        self.toolBar3DViewCamera = QtGui.QToolBar(MainWindow)
        self.toolBar3DViewCamera.setIconSize(QtCore.QSize(32, 32))
        self.toolBar3DViewCamera.setObjectName(_fromUtf8("toolBar3DViewCamera"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar3DViewCamera)
        self.dockWidgetParameters = QtGui.QDockWidget(MainWindow)
        self.dockWidgetParameters.setMinimumSize(QtCore.QSize(200, 43))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/mrsprint/Parameters.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.dockWidgetParameters.setWindowIcon(icon1)
        self.dockWidgetParameters.setObjectName(_fromUtf8("dockWidgetParameters"))
        self.dockWidgetContentsParameters = QtGui.QWidget()
        self.dockWidgetContentsParameters.setObjectName(_fromUtf8("dockWidgetContentsParameters"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.dockWidgetContentsParameters)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.dockWidgetParameters.setWidget(self.dockWidgetContentsParameters)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidgetParameters)
        self.dockWidget2DEditorXY = QtGui.QDockWidget(MainWindow)
        self.dockWidget2DEditorXY.setFeatures(QtGui.QDockWidget.DockWidgetFloatable|QtGui.QDockWidget.DockWidgetMovable)
        self.dockWidget2DEditorXY.setObjectName(_fromUtf8("dockWidget2DEditorXY"))
        self.dockWidgetContents2DEditorXY = QtGui.QWidget()
        self.dockWidgetContents2DEditorXY.setObjectName(_fromUtf8("dockWidgetContents2DEditorXY"))
        self.gridLayout_5 = QtGui.QGridLayout(self.dockWidgetContents2DEditorXY)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.spinBox2DEditorZIndex = QtGui.QSpinBox(self.dockWidgetContents2DEditorXY)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox2DEditorZIndex.sizePolicy().hasHeightForWidth())
        self.spinBox2DEditorZIndex.setSizePolicy(sizePolicy)
        self.spinBox2DEditorZIndex.setMinimum(0)
        self.spinBox2DEditorZIndex.setMaximum(999)
        self.spinBox2DEditorZIndex.setProperty("value", 0)
        self.spinBox2DEditorZIndex.setObjectName(_fromUtf8("spinBox2DEditorZIndex"))
        self.gridLayout_5.addWidget(self.spinBox2DEditorZIndex, 1, 1, 1, 1)
        self.label2DEditorZIndex = QtGui.QLabel(self.dockWidgetContents2DEditorXY)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label2DEditorZIndex.sizePolicy().hasHeightForWidth())
        self.label2DEditorZIndex.setSizePolicy(sizePolicy)
        self.label2DEditorZIndex.setAlignment(QtCore.Qt.AlignCenter)
        self.label2DEditorZIndex.setObjectName(_fromUtf8("label2DEditorZIndex"))
        self.gridLayout_5.addWidget(self.label2DEditorZIndex, 1, 0, 1, 1)
        self.horizontalSlider2DEditorZIndex = QtGui.QSlider(self.dockWidgetContents2DEditorXY)
        self.horizontalSlider2DEditorZIndex.setMinimum(0)
        self.horizontalSlider2DEditorZIndex.setMaximum(999)
        self.horizontalSlider2DEditorZIndex.setProperty("value", 0)
        self.horizontalSlider2DEditorZIndex.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider2DEditorZIndex.setTickPosition(QtGui.QSlider.NoTicks)
        self.horizontalSlider2DEditorZIndex.setObjectName(_fromUtf8("horizontalSlider2DEditorZIndex"))
        self.gridLayout_5.addWidget(self.horizontalSlider2DEditorZIndex, 1, 2, 1, 1)
        self.tableWidget2DEditorXY = QtGui.QTableWidget(self.dockWidgetContents2DEditorXY)
        self.tableWidget2DEditorXY.setObjectName(_fromUtf8("tableWidget2DEditorXY"))
        self.tableWidget2DEditorXY.setColumnCount(0)
        self.tableWidget2DEditorXY.setRowCount(0)
        self.gridLayout_5.addWidget(self.tableWidget2DEditorXY, 0, 0, 1, 3)
        self.dockWidget2DEditorXY.setWidget(self.dockWidgetContents2DEditorXY)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockWidget2DEditorXY)
        self.dockWidget2DEditorYZ = QtGui.QDockWidget(MainWindow)
        self.dockWidget2DEditorYZ.setFeatures(QtGui.QDockWidget.DockWidgetFloatable|QtGui.QDockWidget.DockWidgetMovable)
        self.dockWidget2DEditorYZ.setObjectName(_fromUtf8("dockWidget2DEditorYZ"))
        self.dockWidgetContents2DEditorYZ = QtGui.QWidget()
        self.dockWidgetContents2DEditorYZ.setObjectName(_fromUtf8("dockWidgetContents2DEditorYZ"))
        self.gridLayout_6 = QtGui.QGridLayout(self.dockWidgetContents2DEditorYZ)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.label2DEditorXIndex = QtGui.QLabel(self.dockWidgetContents2DEditorYZ)
        self.label2DEditorXIndex.setObjectName(_fromUtf8("label2DEditorXIndex"))
        self.gridLayout_6.addWidget(self.label2DEditorXIndex, 1, 1, 1, 1)
        self.spinBox2DEditorXIndex = QtGui.QSpinBox(self.dockWidgetContents2DEditorYZ)
        self.spinBox2DEditorXIndex.setMinimum(0)
        self.spinBox2DEditorXIndex.setMaximum(999)
        self.spinBox2DEditorXIndex.setProperty("value", 0)
        self.spinBox2DEditorXIndex.setObjectName(_fromUtf8("spinBox2DEditorXIndex"))
        self.gridLayout_6.addWidget(self.spinBox2DEditorXIndex, 1, 2, 1, 1)
        self.horizontalSlider2DEditorXIndex = QtGui.QSlider(self.dockWidgetContents2DEditorYZ)
        self.horizontalSlider2DEditorXIndex.setMinimum(0)
        self.horizontalSlider2DEditorXIndex.setMaximum(999)
        self.horizontalSlider2DEditorXIndex.setProperty("value", 0)
        self.horizontalSlider2DEditorXIndex.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider2DEditorXIndex.setTickPosition(QtGui.QSlider.NoTicks)
        self.horizontalSlider2DEditorXIndex.setObjectName(_fromUtf8("horizontalSlider2DEditorXIndex"))
        self.gridLayout_6.addWidget(self.horizontalSlider2DEditorXIndex, 1, 3, 1, 1)
        self.tableWidget2DEditorYZ = QtGui.QTableWidget(self.dockWidgetContents2DEditorYZ)
        self.tableWidget2DEditorYZ.setObjectName(_fromUtf8("tableWidget2DEditorYZ"))
        self.tableWidget2DEditorYZ.setColumnCount(0)
        self.tableWidget2DEditorYZ.setRowCount(0)
        self.gridLayout_6.addWidget(self.tableWidget2DEditorYZ, 0, 1, 1, 3)
        self.dockWidget2DEditorYZ.setWidget(self.dockWidgetContents2DEditorYZ)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockWidget2DEditorYZ)
        self.dockWidget2DEditorXZ = QtGui.QDockWidget(MainWindow)
        self.dockWidget2DEditorXZ.setFeatures(QtGui.QDockWidget.DockWidgetFloatable|QtGui.QDockWidget.DockWidgetMovable)
        self.dockWidget2DEditorXZ.setObjectName(_fromUtf8("dockWidget2DEditorXZ"))
        self.dockWidgetContents2DEditorXZ = QtGui.QWidget()
        self.dockWidgetContents2DEditorXZ.setObjectName(_fromUtf8("dockWidgetContents2DEditorXZ"))
        self.gridLayout_7 = QtGui.QGridLayout(self.dockWidgetContents2DEditorXZ)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.label2DEditorYIndex = QtGui.QLabel(self.dockWidgetContents2DEditorXZ)
        self.label2DEditorYIndex.setObjectName(_fromUtf8("label2DEditorYIndex"))
        self.gridLayout_7.addWidget(self.label2DEditorYIndex, 1, 0, 1, 1)
        self.spinBox2DEditorYIndex = QtGui.QSpinBox(self.dockWidgetContents2DEditorXZ)
        self.spinBox2DEditorYIndex.setMinimum(0)
        self.spinBox2DEditorYIndex.setMaximum(999)
        self.spinBox2DEditorYIndex.setProperty("value", 0)
        self.spinBox2DEditorYIndex.setObjectName(_fromUtf8("spinBox2DEditorYIndex"))
        self.gridLayout_7.addWidget(self.spinBox2DEditorYIndex, 1, 1, 1, 1)
        self.horizontalSlider2DEditorYIndex = QtGui.QSlider(self.dockWidgetContents2DEditorXZ)
        self.horizontalSlider2DEditorYIndex.setMinimum(0)
        self.horizontalSlider2DEditorYIndex.setMaximum(999)
        self.horizontalSlider2DEditorYIndex.setProperty("value", 0)
        self.horizontalSlider2DEditorYIndex.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider2DEditorYIndex.setTickPosition(QtGui.QSlider.NoTicks)
        self.horizontalSlider2DEditorYIndex.setObjectName(_fromUtf8("horizontalSlider2DEditorYIndex"))
        self.gridLayout_7.addWidget(self.horizontalSlider2DEditorYIndex, 1, 2, 1, 1)
        self.tableWidget2DEditorXZ = QtGui.QTableWidget(self.dockWidgetContents2DEditorXZ)
        self.tableWidget2DEditorXZ.setObjectName(_fromUtf8("tableWidget2DEditorXZ"))
        self.tableWidget2DEditorXZ.setColumnCount(0)
        self.tableWidget2DEditorXZ.setRowCount(0)
        self.gridLayout_7.addWidget(self.tableWidget2DEditorXZ, 0, 0, 1, 3)
        self.dockWidget2DEditorXZ.setWidget(self.dockWidgetContents2DEditorXZ)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockWidget2DEditorXZ)
        self.toolBarContext = QtGui.QToolBar(MainWindow)
        self.toolBarContext.setIconSize(QtCore.QSize(42, 42))
        self.toolBarContext.setObjectName(_fromUtf8("toolBarContext"))
        MainWindow.addToolBar(QtCore.Qt.LeftToolBarArea, self.toolBarContext)
        self.toolBar3DView = QtGui.QToolBar(MainWindow)
        self.toolBar3DView.setIconSize(QtCore.QSize(32, 32))
        self.toolBar3DView.setObjectName(_fromUtf8("toolBar3DView"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar3DView)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)
        self.toolBarFile = QtGui.QToolBar(MainWindow)
        self.toolBarFile.setIconSize(QtCore.QSize(32, 32))
        self.toolBarFile.setObjectName(_fromUtf8("toolBarFile"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBarFile)
        self.toolBarFieldInhomogeneity = QtGui.QToolBar(MainWindow)
        self.toolBarFieldInhomogeneity.setIconSize(QtCore.QSize(42, 42))
        self.toolBarFieldInhomogeneity.setObjectName(_fromUtf8("toolBarFieldInhomogeneity"))
        MainWindow.addToolBar(QtCore.Qt.LeftToolBarArea, self.toolBarFieldInhomogeneity)
        self.toolBarSimulator = QtGui.QToolBar(MainWindow)
        self.toolBarSimulator.setIconSize(QtCore.QSize(42, 42))
        self.toolBarSimulator.setObjectName(_fromUtf8("toolBarSimulator"))
        MainWindow.addToolBar(QtCore.Qt.LeftToolBarArea, self.toolBarSimulator)
        self.dockWidgetExplorer = QtGui.QDockWidget(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/mrsprint/Explorer.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.dockWidgetExplorer.setWindowIcon(icon2)
        self.dockWidgetExplorer.setObjectName(_fromUtf8("dockWidgetExplorer"))
        self.dockWidgetContentsExplorer = QtGui.QWidget()
        self.dockWidgetContentsExplorer.setObjectName(_fromUtf8("dockWidgetContentsExplorer"))
        self.verticalLayout = QtGui.QVBoxLayout(self.dockWidgetContentsExplorer)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.listWidgetExplorer = QtGui.QListWidget(self.dockWidgetContentsExplorer)
        self.listWidgetExplorer.setObjectName(_fromUtf8("listWidgetExplorer"))
        self.verticalLayout.addWidget(self.listWidgetExplorer)
        self.dockWidgetExplorer.setWidget(self.dockWidgetContentsExplorer)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidgetExplorer)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1002, 28))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuFile = QtGui.QMenu(self.menuBar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuSampleElement = QtGui.QMenu(self.menuBar)
        self.menuSampleElement.setObjectName(_fromUtf8("menuSampleElement"))
        self.menuHelp = QtGui.QMenu(self.menuBar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        self.menuConfiguration = QtGui.QMenu(self.menuBar)
        self.menuConfiguration.setObjectName(_fromUtf8("menuConfiguration"))
        self.menu2DEditor = QtGui.QMenu(self.menuBar)
        self.menu2DEditor.setObjectName(_fromUtf8("menu2DEditor"))
        self.menu3DView = QtGui.QMenu(self.menuBar)
        self.menu3DView.setObjectName(_fromUtf8("menu3DView"))
        self.menuContext = QtGui.QMenu(self.menuBar)
        self.menuContext.setObjectName(_fromUtf8("menuContext"))
        self.menuSystem = QtGui.QMenu(self.menuBar)
        self.menuSystem.setObjectName(_fromUtf8("menuSystem"))
        self.menuSimulator = QtGui.QMenu(self.menuBar)
        self.menuSimulator.setObjectName(_fromUtf8("menuSimulator"))
        self.menuViews = QtGui.QMenu(self.menuBar)
        self.menuViews.setObjectName(_fromUtf8("menuViews"))
        self.menuViews3DPlot = QtGui.QMenu(self.menuViews)
        self.menuViews3DPlot.setObjectName(_fromUtf8("menuViews3DPlot"))
        self.menuViews2DPlot = QtGui.QMenu(self.menuViews)
        self.menuViews2DPlot.setObjectName(_fromUtf8("menuViews2DPlot"))
        MainWindow.setMenuBar(self.menuBar)
        self.dockWidgetLog = QtGui.QDockWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidgetLog.sizePolicy().hasHeightForWidth())
        self.dockWidgetLog.setSizePolicy(sizePolicy)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/mrsprint/Log.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.dockWidgetLog.setWindowIcon(icon3)
        self.dockWidgetLog.setObjectName(_fromUtf8("dockWidgetLog"))
        self.dockWidgetContentsLog = QtGui.QWidget()
        self.dockWidgetContentsLog.setObjectName(_fromUtf8("dockWidgetContentsLog"))
        self.gridLayout = QtGui.QGridLayout(self.dockWidgetContentsLog)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.textEditLog = QtGui.QTextEdit(self.dockWidgetContentsLog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEditLog.sizePolicy().hasHeightForWidth())
        self.textEditLog.setSizePolicy(sizePolicy)
        self.textEditLog.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier 10 Pitch"))
        font.setPointSize(10)
        self.textEditLog.setFont(font)
        self.textEditLog.setStyleSheet(_fromUtf8("background-color: rgb(20, 20, 20);"))
        self.textEditLog.setAutoFormatting(QtGui.QTextEdit.AutoBulletList)
        self.textEditLog.setReadOnly(True)
        self.textEditLog.setObjectName(_fromUtf8("textEditLog"))
        self.gridLayout.addWidget(self.textEditLog, 0, 0, 2, 1)
        self.comboBoxLogLevel = QtGui.QComboBox(self.dockWidgetContentsLog)
        self.comboBoxLogLevel.setObjectName(_fromUtf8("comboBoxLogLevel"))
        self.comboBoxLogLevel.addItem(_fromUtf8(""))
        self.comboBoxLogLevel.addItem(_fromUtf8(""))
        self.comboBoxLogLevel.addItem(_fromUtf8(""))
        self.comboBoxLogLevel.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboBoxLogLevel, 0, 1, 1, 1)
        self.pushButtonLogReset = QtGui.QPushButton(self.dockWidgetContentsLog)
        self.pushButtonLogReset.setText(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/mrsprint/Quit.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonLogReset.setIcon(icon4)
        self.pushButtonLogReset.setObjectName(_fromUtf8("pushButtonLogReset"))
        self.gridLayout.addWidget(self.pushButtonLogReset, 1, 1, 1, 1)
        self.dockWidgetLog.setWidget(self.dockWidgetContentsLog)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.dockWidgetLog)
        self.actionSampleElementT1 = QtGui.QAction(MainWindow)
        self.actionSampleElementT1.setCheckable(True)
        self.actionSampleElementT1.setChecked(True)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/mrsprint/SampleElementT1.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSampleElementT1.setIcon(icon5)
        self.actionSampleElementT1.setIconVisibleInMenu(True)
        self.actionSampleElementT1.setObjectName(_fromUtf8("actionSampleElementT1"))
        self.actionSampleElementT2 = QtGui.QAction(MainWindow)
        self.actionSampleElementT2.setCheckable(True)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/mrsprint/SampleElementT2.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSampleElementT2.setIcon(icon6)
        self.actionSampleElementT2.setIconVisibleInMenu(True)
        self.actionSampleElementT2.setObjectName(_fromUtf8("actionSampleElementT2"))
        self.actionSampleElementRho = QtGui.QAction(MainWindow)
        self.actionSampleElementRho.setCheckable(True)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/mrsprint/SampleElementRho.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSampleElementRho.setIcon(icon7)
        self.actionSampleElementRho.setIconVisibleInMenu(True)
        self.actionSampleElementRho.setObjectName(_fromUtf8("actionSampleElementRho"))
        self.action2DEditorXY = QtGui.QAction(MainWindow)
        self.action2DEditorXY.setCheckable(True)
        self.action2DEditorXY.setChecked(False)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/mrsprint/2DEditorXY.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action2DEditorXY.setIcon(icon8)
        self.action2DEditorXY.setIconVisibleInMenu(True)
        self.action2DEditorXY.setObjectName(_fromUtf8("action2DEditorXY"))
        self.action2DEditorXZ = QtGui.QAction(MainWindow)
        self.action2DEditorXZ.setCheckable(True)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/mrsprint/2DEditorXZ.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action2DEditorXZ.setIcon(icon9)
        self.action2DEditorXZ.setIconVisibleInMenu(True)
        self.action2DEditorXZ.setObjectName(_fromUtf8("action2DEditorXZ"))
        self.action2DEditorYZ = QtGui.QAction(MainWindow)
        self.action2DEditorYZ.setCheckable(True)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/mrsprint/2DEditorYZ.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action2DEditorYZ.setIcon(icon10)
        self.action2DEditorYZ.setIconVisibleInMenu(True)
        self.action2DEditorYZ.setObjectName(_fromUtf8("action2DEditorYZ"))
        self.action3DViewColor = QtGui.QAction(MainWindow)
        self.action3DViewColor.setCheckable(True)
        self.action3DViewColor.setChecked(True)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8(":/mrsprint/3DViewColor.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action3DViewColor.setIcon(icon11)
        self.action3DViewColor.setIconVisibleInMenu(True)
        self.action3DViewColor.setObjectName(_fromUtf8("action3DViewColor"))
        self.actionFileNew = QtGui.QAction(MainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(_fromUtf8(":/mrsprint/FileNew.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFileNew.setIcon(icon12)
        self.actionFileNew.setIconVisibleInMenu(True)
        self.actionFileNew.setObjectName(_fromUtf8("actionFileNew"))
        self.actionFileOpen = QtGui.QAction(MainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(_fromUtf8(":/mrsprint/FileOpen.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFileOpen.setIcon(icon13)
        self.actionFileOpen.setIconVisibleInMenu(True)
        self.actionFileOpen.setObjectName(_fromUtf8("actionFileOpen"))
        self.actionFileSave = QtGui.QAction(MainWindow)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(_fromUtf8(":/mrsprint/FileSave.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFileSave.setIcon(icon14)
        self.actionFileSave.setIconVisibleInMenu(True)
        self.actionFileSave.setObjectName(_fromUtf8("actionFileSave"))
        self.actionFileSaveAs = QtGui.QAction(MainWindow)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(_fromUtf8(":/mrsprint/FileSaveAs.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFileSaveAs.setIcon(icon15)
        self.actionFileSaveAs.setIconVisibleInMenu(True)
        self.actionFileSaveAs.setObjectName(_fromUtf8("actionFileSaveAs"))
        self.actionFileClose = QtGui.QAction(MainWindow)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(_fromUtf8(":/mrsprint/FileClose.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFileClose.setIcon(icon16)
        self.actionFileClose.setIconVisibleInMenu(True)
        self.actionFileClose.setObjectName(_fromUtf8("actionFileClose"))
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setIcon(icon4)
        self.actionQuit.setIconVisibleInMenu(True)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionFileExamples = QtGui.QAction(MainWindow)
        self.actionFileExamples.setIconVisibleInMenu(True)
        self.actionFileExamples.setObjectName(_fromUtf8("actionFileExamples"))
        self.action2DEditorXYZ = QtGui.QAction(MainWindow)
        self.action2DEditorXYZ.setCheckable(True)
        self.action2DEditorXYZ.setChecked(True)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(_fromUtf8(":/mrsprint/2DEditorXYZ.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action2DEditorXYZ.setIcon(icon17)
        self.action2DEditorXYZ.setIconVisibleInMenu(True)
        self.action2DEditorXYZ.setObjectName(_fromUtf8("action2DEditorXYZ"))
        self.actionConfigurationPreferences = QtGui.QAction(MainWindow)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(_fromUtf8(":/mrsprint/Settings.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionConfigurationPreferences.setIcon(icon18)
        self.actionConfigurationPreferences.setIconVisibleInMenu(True)
        self.actionConfigurationPreferences.setObjectName(_fromUtf8("actionConfigurationPreferences"))
        self.action3DView = QtGui.QAction(MainWindow)
        self.action3DView.setCheckable(True)
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(_fromUtf8(":/mrsprint/3DView.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action3DView.setIcon(icon19)
        self.action3DView.setIconVisibleInMenu(True)
        self.action3DView.setObjectName(_fromUtf8("action3DView"))
        self.action2DEditorGradient = QtGui.QAction(MainWindow)
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap(_fromUtf8(":/mrsprint/2DEditorGradient.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action2DEditorGradient.setIcon(icon20)
        self.action2DEditorGradient.setIconVisibleInMenu(True)
        self.action2DEditorGradient.setObjectName(_fromUtf8("action2DEditorGradient"))
        self.action3DViewCameraXYZ = QtGui.QAction(MainWindow)
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap(_fromUtf8(":/mrsprint/3DViewXYZ.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action3DViewCameraXYZ.setIcon(icon21)
        self.action3DViewCameraXYZ.setIconVisibleInMenu(True)
        self.action3DViewCameraXYZ.setObjectName(_fromUtf8("action3DViewCameraXYZ"))
        self.action3DViewCameraXY = QtGui.QAction(MainWindow)
        icon22 = QtGui.QIcon()
        icon22.addPixmap(QtGui.QPixmap(_fromUtf8(":/mrsprint/3DViewXY.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action3DViewCameraXY.setIcon(icon22)
        self.action3DViewCameraXY.setIconVisibleInMenu(True)
        self.action3DViewCameraXY.setObjectName(_fromUtf8("action3DViewCameraXY"))
        self.action3DViewCameraXZ = QtGui.QAction(MainWindow)
        icon23 = QtGui.QIcon()
        icon23.addPixmap(QtGui.QPixmap(_fromUtf8(":/mrsprint/3DViewXZ.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action3DViewCameraXZ.setIcon(icon23)
        self.action3DViewCameraXZ.setIconVisibleInMenu(True)
        self.action3DViewCameraXZ.setObjectName(_fromUtf8("action3DViewCameraXZ"))
        self.action3DViewCameraYZ = QtGui.QAction(MainWindow)
        icon24 = QtGui.QIcon()
        icon24.addPixmap(QtGui.QPixmap(_fromUtf8(":/mrsprint/3DViewYZ.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action3DViewCameraYZ.setIcon(icon24)
        self.action3DViewCameraYZ.setIconVisibleInMenu(True)
        self.action3DViewCameraYZ.setObjectName(_fromUtf8("action3DViewCameraYZ"))
        self.actionContextSample = QtGui.QAction(MainWindow)
        self.actionContextSample.setCheckable(True)
        self.actionContextSample.setChecked(True)
        icon25 = QtGui.QIcon()
        icon25.addPixmap(QtGui.QPixmap(_fromUtf8(":/mrsprint/ContextSubject.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionContextSample.setIcon(icon25)
        self.actionContextSample.setIconVisibleInMenu(True)
        self.actionContextSample.setObjectName(_fromUtf8("actionContextSample"))
        self.actionContextSystem = QtGui.QAction(MainWindow)
        self.actionContextSystem.setCheckable(True)
        icon26 = QtGui.QIcon()
        icon26.addPixmap(QtGui.QPixmap(_fromUtf8(":/mrsprint/ContextSystem.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionContextSystem.setIcon(icon26)
        self.actionContextSystem.setIconVisibleInMenu(True)
        self.actionContextSystem.setObjectName(_fromUtf8("actionContextSystem"))
        self.actionContextSequence = QtGui.QAction(MainWindow)
        self.actionContextSequence.setCheckable(True)
        icon27 = QtGui.QIcon()
        icon27.addPixmap(QtGui.QPixmap(_fromUtf8(":/mrsprint/ContextSequence.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionContextSequence.setIcon(icon27)
        self.actionContextSequence.setIconVisibleInMenu(True)
        self.actionContextSequence.setObjectName(_fromUtf8("actionContextSequence"))
        self.actionContextProcessing = QtGui.QAction(MainWindow)
        self.actionContextProcessing.setCheckable(True)
        icon28 = QtGui.QIcon()
        icon28.addPixmap(QtGui.QPixmap(_fromUtf8(":/mrsprint/ContextProcessing.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionContextProcessing.setIcon(icon28)
        self.actionContextProcessing.setIconVisibleInMenu(True)
        self.actionContextProcessing.setObjectName(_fromUtf8("actionContextProcessing"))
        self.action2DEditorColor = QtGui.QAction(MainWindow)
        self.action2DEditorColor.setCheckable(True)
        self.action2DEditorColor.setChecked(True)
        icon29 = QtGui.QIcon()
        icon29.addPixmap(QtGui.QPixmap(_fromUtf8(":/mrsprint/2DEditorColor.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action2DEditorColor.setIcon(icon29)
        self.action2DEditorColor.setIconVisibleInMenu(True)
        self.action2DEditorColor.setObjectName(_fromUtf8("action2DEditorColor"))
        self.actionSampleElementAll = QtGui.QAction(MainWindow)
        self.actionSampleElementAll.setCheckable(True)
        icon30 = QtGui.QIcon()
        icon30.addPixmap(QtGui.QPixmap(_fromUtf8(":/mrsprint/SampleElementAll.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSampleElementAll.setIcon(icon30)
        self.actionSampleElementAll.setIconVisibleInMenu(True)
        self.actionSampleElementAll.setObjectName(_fromUtf8("actionSampleElementAll"))
        self.action2DEditor = QtGui.QAction(MainWindow)
        self.action2DEditor.setCheckable(True)
        icon31 = QtGui.QIcon()
        icon31.addPixmap(QtGui.QPixmap(_fromUtf8(":/mrsprint/2DEditor.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action2DEditor.setIcon(icon31)
        self.action2DEditor.setIconVisibleInMenu(True)
        self.action2DEditor.setObjectName(_fromUtf8("action2DEditor"))
        self.action3DViewXGrid = QtGui.QAction(MainWindow)
        self.action3DViewXGrid.setCheckable(True)
        self.action3DViewXGrid.setChecked(True)
        icon32 = QtGui.QIcon()
        icon32.addPixmap(QtGui.QPixmap(_fromUtf8(":/mrsprint/3DViewGridX.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action3DViewXGrid.setIcon(icon32)
        self.action3DViewXGrid.setIconVisibleInMenu(True)
        self.action3DViewXGrid.setObjectName(_fromUtf8("action3DViewXGrid"))
        self.action3DViewYGrid = QtGui.QAction(MainWindow)
        self.action3DViewYGrid.setCheckable(True)
        self.action3DViewYGrid.setChecked(True)
        icon33 = QtGui.QIcon()
        icon33.addPixmap(QtGui.QPixmap(_fromUtf8(":/mrsprint/3DViewGridY.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action3DViewYGrid.setIcon(icon33)
        self.action3DViewYGrid.setIconVisibleInMenu(True)
        self.action3DViewYGrid.setObjectName(_fromUtf8("action3DViewYGrid"))
        self.action3DViewZGrid = QtGui.QAction(MainWindow)
        self.action3DViewZGrid.setCheckable(True)
        self.action3DViewZGrid.setChecked(True)
        icon34 = QtGui.QIcon()
        icon34.addPixmap(QtGui.QPixmap(_fromUtf8(":/mrsprint/3DViewGridZ.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action3DViewZGrid.setIcon(icon34)
        self.action3DViewZGrid.setIconVisibleInMenu(True)
        self.action3DViewZGrid.setObjectName(_fromUtf8("action3DViewZGrid"))
        self.action3DViewXYZAxis = QtGui.QAction(MainWindow)
        self.action3DViewXYZAxis.setCheckable(True)
        self.action3DViewXYZAxis.setChecked(True)
        icon35 = QtGui.QIcon()
        icon35.addPixmap(QtGui.QPixmap(_fromUtf8(":/mrsprint/3DViewAxisXYZ.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action3DViewXYZAxis.setIcon(icon35)
        self.action3DViewXYZAxis.setIconVisibleInMenu(True)
        self.action3DViewXYZAxis.setObjectName(_fromUtf8("action3DViewXYZAxis"))
        self.action3DViewInvertBackground = QtGui.QAction(MainWindow)
        self.action3DViewInvertBackground.setCheckable(True)
        icon36 = QtGui.QIcon()
        icon36.addPixmap(QtGui.QPixmap(_fromUtf8(":/mrsprint/3DViewInvertBackground.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action3DViewInvertBackground.setIcon(icon36)
        self.action3DViewInvertBackground.setIconVisibleInMenu(True)
        self.action3DViewInvertBackground.setObjectName(_fromUtf8("action3DViewInvertBackground"))
        self.action2DEditorInvertBackground = QtGui.QAction(MainWindow)
        self.action2DEditorInvertBackground.setCheckable(True)
        self.action2DEditorInvertBackground.setIcon(icon36)
        self.action2DEditorInvertBackground.setIconVisibleInMenu(True)
        self.action2DEditorInvertBackground.setObjectName(_fromUtf8("action2DEditorInvertBackground"))
        self.actionContextSimulator = QtGui.QAction(MainWindow)
        self.actionContextSimulator.setCheckable(True)
        icon37 = QtGui.QIcon()
        icon37.addPixmap(QtGui.QPixmap(_fromUtf8(":/mrsprint/ContextSimulator.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionContextSimulator.setIcon(icon37)
        self.actionContextSimulator.setIconVisibleInMenu(True)
        self.actionContextSimulator.setObjectName(_fromUtf8("actionContextSimulator"))
        self.actionFieldInhomogeneityB0X = QtGui.QAction(MainWindow)
        self.actionFieldInhomogeneityB0X.setCheckable(True)
        icon38 = QtGui.QIcon()
        icon38.addPixmap(QtGui.QPixmap(_fromUtf8(":/mrsprint/FieldInhomogeneityB0X.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFieldInhomogeneityB0X.setIcon(icon38)
        self.actionFieldInhomogeneityB0X.setIconVisibleInMenu(True)
        self.actionFieldInhomogeneityB0X.setObjectName(_fromUtf8("actionFieldInhomogeneityB0X"))
        self.actionFieldInhomogeneityB0Y = QtGui.QAction(MainWindow)
        self.actionFieldInhomogeneityB0Y.setCheckable(True)
        icon39 = QtGui.QIcon()
        icon39.addPixmap(QtGui.QPixmap(_fromUtf8(":/mrsprint/FieldInhomogeneityB0Y.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFieldInhomogeneityB0Y.setIcon(icon39)
        self.actionFieldInhomogeneityB0Y.setIconVisibleInMenu(True)
        self.actionFieldInhomogeneityB0Y.setObjectName(_fromUtf8("actionFieldInhomogeneityB0Y"))
        self.actionFieldInhomogeneityB0Z = QtGui.QAction(MainWindow)
        self.actionFieldInhomogeneityB0Z.setCheckable(True)
        icon40 = QtGui.QIcon()
        icon40.addPixmap(QtGui.QPixmap(_fromUtf8(":/mrsprint/FieldInhomogeneityB0Z.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFieldInhomogeneityB0Z.setIcon(icon40)
        self.actionFieldInhomogeneityB0Z.setIconVisibleInMenu(True)
        self.actionFieldInhomogeneityB0Z.setObjectName(_fromUtf8("actionFieldInhomogeneityB0Z"))
        self.actionFieldInhomogeneityAll = QtGui.QAction(MainWindow)
        self.actionFieldInhomogeneityAll.setCheckable(True)
        icon41 = QtGui.QIcon()
        icon41.addPixmap(QtGui.QPixmap(_fromUtf8(":/mrsprint/FieldInhomogeneityB0Sum.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFieldInhomogeneityAll.setIcon(icon41)
        self.actionFieldInhomogeneityAll.setIconVisibleInMenu(True)
        self.actionFieldInhomogeneityAll.setObjectName(_fromUtf8("actionFieldInhomogeneityAll"))
        self.actionSimulatorPlay = QtGui.QAction(MainWindow)
        self.actionSimulatorPlay.setCheckable(True)
        icon42 = QtGui.QIcon()
        icon42.addPixmap(QtGui.QPixmap(_fromUtf8(":/mrsprint/SimulatorPlay.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSimulatorPlay.setIcon(icon42)
        self.actionSimulatorPlay.setIconVisibleInMenu(True)
        self.actionSimulatorPlay.setObjectName(_fromUtf8("actionSimulatorPlay"))
        self.actionSimulatorStop = QtGui.QAction(MainWindow)
        self.actionSimulatorStop.setCheckable(True)
        icon43 = QtGui.QIcon()
        icon43.addPixmap(QtGui.QPixmap(_fromUtf8(":/mrsprint/SimulatorStop.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSimulatorStop.setIcon(icon43)
        self.actionSimulatorStop.setIconVisibleInMenu(True)
        self.actionSimulatorStop.setObjectName(_fromUtf8("actionSimulatorStop"))
        self.actionSimulatorPause = QtGui.QAction(MainWindow)
        self.actionSimulatorPause.setCheckable(True)
        icon44 = QtGui.QIcon()
        icon44.addPixmap(QtGui.QPixmap(_fromUtf8(":/mrsprint/SimulatorPause.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSimulatorPause.setIcon(icon44)
        self.actionSimulatorPause.setIconVisibleInMenu(True)
        self.actionSimulatorPause.setObjectName(_fromUtf8("actionSimulatorPause"))
        self.actionSimulatorCalculate = QtGui.QAction(MainWindow)
        self.actionSimulatorCalculate.setCheckable(True)
        icon45 = QtGui.QIcon()
        icon45.addPixmap(QtGui.QPixmap(_fromUtf8(":/mrsprint/SimulatorCalculate.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSimulatorCalculate.setIcon(icon45)
        self.actionSimulatorCalculate.setIconVisibleInMenu(True)
        self.actionSimulatorCalculate.setObjectName(_fromUtf8("actionSimulatorCalculate"))
        self.actionContextProtocol = QtGui.QAction(MainWindow)
        self.actionContextProtocol.setCheckable(True)
        self.actionContextProtocol.setEnabled(False)
        icon46 = QtGui.QIcon()
        icon46.addPixmap(QtGui.QPixmap(_fromUtf8(":/mrsprint/ContextProtocol.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionContextProtocol.setIcon(icon46)
        self.actionContextProtocol.setObjectName(_fromUtf8("actionContextProtocol"))
        self.actionSampleElementNucleus = QtGui.QAction(MainWindow)
        self.actionSampleElementNucleus.setEnabled(False)
        icon47 = QtGui.QIcon()
        icon47.addPixmap(QtGui.QPixmap(_fromUtf8(":/mrsprint/Nucleus.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSampleElementNucleus.setIcon(icon47)
        self.actionSampleElementNucleus.setObjectName(_fromUtf8("actionSampleElementNucleus"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setIcon(icon)
        self.actionAbout.setIconVisibleInMenu(False)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionViewsParameters = QtGui.QAction(MainWindow)
        self.actionViewsParameters.setCheckable(True)
        self.actionViewsParameters.setIcon(icon1)
        self.actionViewsParameters.setIconVisibleInMenu(True)
        self.actionViewsParameters.setObjectName(_fromUtf8("actionViewsParameters"))
        self.actionViewsExplorer = QtGui.QAction(MainWindow)
        self.actionViewsExplorer.setCheckable(True)
        self.actionViewsExplorer.setIcon(icon2)
        self.actionViewsExplorer.setIconVisibleInMenu(True)
        self.actionViewsExplorer.setObjectName(_fromUtf8("actionViewsExplorer"))
        self.actionViews2DEditor = QtGui.QAction(MainWindow)
        self.actionViews2DEditor.setCheckable(True)
        self.actionViews2DEditor.setIconVisibleInMenu(False)
        self.actionViews2DEditor.setObjectName(_fromUtf8("actionViews2DEditor"))
        self.actionViews2DProcessing = QtGui.QAction(MainWindow)
        self.actionViews2DProcessing.setCheckable(True)
        self.actionViews2DProcessing.setObjectName(_fromUtf8("actionViews2DProcessing"))
        self.actionViews2DMagnetization = QtGui.QAction(MainWindow)
        self.actionViews2DMagnetization.setCheckable(True)
        self.actionViews2DMagnetization.setObjectName(_fromUtf8("actionViews2DMagnetization"))
        self.actionViewsLog = QtGui.QAction(MainWindow)
        self.actionViewsLog.setCheckable(True)
        self.actionViewsLog.setIcon(icon3)
        self.actionViewsLog.setIconVisibleInMenu(True)
        self.actionViewsLog.setObjectName(_fromUtf8("actionViewsLog"))
        self.actionViews3DSample = QtGui.QAction(MainWindow)
        self.actionViews3DSample.setCheckable(True)
        self.actionViews3DSample.setObjectName(_fromUtf8("actionViews3DSample"))
        self.actionViews3DSystem = QtGui.QAction(MainWindow)
        self.actionViews3DSystem.setCheckable(True)
        self.actionViews3DSystem.setObjectName(_fromUtf8("actionViews3DSystem"))
        self.actionViews2DKSpace = QtGui.QAction(MainWindow)
        self.actionViews2DKSpace.setCheckable(True)
        self.actionViews2DKSpace.setObjectName(_fromUtf8("actionViews2DKSpace"))
        self.actionViews3DSimulator = QtGui.QAction(MainWindow)
        self.actionViews3DSimulator.setCheckable(True)
        self.actionViews3DSimulator.setObjectName(_fromUtf8("actionViews3DSimulator"))
        self.toolBarSampleElement.addAction(self.actionSampleElementT1)
        self.toolBarSampleElement.addAction(self.actionSampleElementT2)
        self.toolBarSampleElement.addAction(self.actionSampleElementRho)
        self.toolBarSampleElement.addSeparator()
        self.toolBar2DEditor.addAction(self.action2DEditorXY)
        self.toolBar2DEditor.addAction(self.action2DEditorXZ)
        self.toolBar2DEditor.addAction(self.action2DEditorYZ)
        self.toolBar2DEditor.addSeparator()
        self.toolBar2DEditor.addAction(self.action2DEditorXYZ)
        self.toolBar2DEditor.addSeparator()
        self.toolBar2DEditor.addAction(self.action2DEditorColor)
        self.toolBar2DEditor.addSeparator()
        self.toolBar2DEditor.addAction(self.action2DEditorGradient)
        self.toolBar3DViewCamera.addAction(self.action3DViewCameraXY)
        self.toolBar3DViewCamera.addAction(self.action3DViewCameraXZ)
        self.toolBar3DViewCamera.addAction(self.action3DViewCameraYZ)
        self.toolBar3DViewCamera.addSeparator()
        self.toolBar3DViewCamera.addAction(self.action3DViewCameraXYZ)
        self.toolBarContext.addAction(self.actionContextSample)
        self.toolBarContext.addAction(self.actionContextSystem)
        self.toolBarContext.addAction(self.actionContextSequence)
        self.toolBarContext.addAction(self.actionContextSimulator)
        self.toolBarContext.addAction(self.actionContextProcessing)
        self.toolBarContext.addSeparator()
        self.toolBarContext.addAction(self.actionContextProtocol)
        self.toolBar3DView.addAction(self.action3DViewColor)
        self.toolBar3DView.addSeparator()
        self.toolBar3DView.addAction(self.action3DViewXGrid)
        self.toolBar3DView.addAction(self.action3DViewYGrid)
        self.toolBar3DView.addAction(self.action3DViewZGrid)
        self.toolBar3DView.addSeparator()
        self.toolBar3DView.addAction(self.action3DViewXYZAxis)
        self.toolBarFile.addAction(self.actionFileNew)
        self.toolBarFile.addAction(self.actionFileOpen)
        self.toolBarFile.addAction(self.actionFileSave)
        self.toolBarFieldInhomogeneity.addAction(self.actionFieldInhomogeneityB0X)
        self.toolBarFieldInhomogeneity.addAction(self.actionFieldInhomogeneityB0Y)
        self.toolBarFieldInhomogeneity.addAction(self.actionFieldInhomogeneityB0Z)
        self.toolBarFieldInhomogeneity.addSeparator()
        self.toolBarSimulator.addAction(self.actionSimulatorPlay)
        self.toolBarSimulator.addAction(self.actionSimulatorPause)
        self.toolBarSimulator.addAction(self.actionSimulatorStop)
        self.toolBarSimulator.addSeparator()
        self.toolBarSimulator.addAction(self.actionSimulatorCalculate)
        self.menuFile.addAction(self.actionFileNew)
        self.menuFile.addAction(self.actionFileOpen)
        self.menuFile.addAction(self.actionFileExamples)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionFileSave)
        self.menuFile.addAction(self.actionFileSaveAs)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionFileClose)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuSampleElement.addAction(self.actionSampleElementT1)
        self.menuSampleElement.addAction(self.actionSampleElementT2)
        self.menuSampleElement.addAction(self.actionSampleElementRho)
        self.menuSampleElement.addSeparator()
        self.menuSampleElement.addAction(self.actionSampleElementNucleus)
        self.menuHelp.addAction(self.actionAbout)
        self.menuConfiguration.addAction(self.actionConfigurationPreferences)
        self.menu2DEditor.addAction(self.action2DEditorXY)
        self.menu2DEditor.addAction(self.action2DEditorXZ)
        self.menu2DEditor.addAction(self.action2DEditorYZ)
        self.menu2DEditor.addSeparator()
        self.menu2DEditor.addAction(self.action2DEditorXYZ)
        self.menu2DEditor.addSeparator()
        self.menu2DEditor.addAction(self.action2DEditorColor)
        self.menu2DEditor.addSeparator()
        self.menu2DEditor.addAction(self.action2DEditor)
        self.menu2DEditor.addSeparator()
        self.menu2DEditor.addAction(self.action2DEditorInvertBackground)
        self.menu3DView.addSeparator()
        self.menu3DView.addAction(self.action3DViewCameraXY)
        self.menu3DView.addAction(self.action3DViewCameraXZ)
        self.menu3DView.addAction(self.action3DViewCameraYZ)
        self.menu3DView.addSeparator()
        self.menu3DView.addAction(self.action3DViewCameraXYZ)
        self.menu3DView.addSeparator()
        self.menu3DView.addAction(self.action3DViewXGrid)
        self.menu3DView.addAction(self.action3DViewYGrid)
        self.menu3DView.addAction(self.action3DViewZGrid)
        self.menu3DView.addSeparator()
        self.menu3DView.addAction(self.action3DViewXYZAxis)
        self.menu3DView.addSeparator()
        self.menu3DView.addAction(self.action3DViewColor)
        self.menu3DView.addSeparator()
        self.menu3DView.addAction(self.action3DViewInvertBackground)
        self.menu3DView.addSeparator()
        self.menu3DView.addAction(self.action3DView)
        self.menuContext.addAction(self.actionContextSample)
        self.menuContext.addAction(self.actionContextSystem)
        self.menuContext.addAction(self.actionContextSequence)
        self.menuContext.addAction(self.actionContextProcessing)
        self.menuContext.addAction(self.actionContextSimulator)
        self.menuContext.addSeparator()
        self.menuContext.addAction(self.actionContextProtocol)
        self.menuSystem.addAction(self.actionFieldInhomogeneityB0X)
        self.menuSystem.addAction(self.actionFieldInhomogeneityB0Y)
        self.menuSystem.addAction(self.actionFieldInhomogeneityB0Z)
        self.menuSystem.addSeparator()
        self.menuSystem.addAction(self.actionFieldInhomogeneityAll)
        self.menuSimulator.addAction(self.actionSimulatorPlay)
        self.menuSimulator.addAction(self.actionSimulatorStop)
        self.menuSimulator.addAction(self.actionSimulatorPause)
        self.menuSimulator.addSeparator()
        self.menuSimulator.addAction(self.actionSimulatorCalculate)
        self.menuViews3DPlot.addAction(self.actionViews3DSample)
        self.menuViews3DPlot.addAction(self.actionViews3DSystem)
        self.menuViews3DPlot.addAction(self.actionViews3DSimulator)
        self.menuViews2DPlot.addAction(self.actionViews2DKSpace)
        self.menuViews2DPlot.addAction(self.actionViews2DMagnetization)
        self.menuViews2DPlot.addAction(self.actionViews2DProcessing)
        self.menuViews.addAction(self.actionViewsParameters)
        self.menuViews.addAction(self.actionViewsExplorer)
        self.menuViews.addSeparator()
        self.menuViews.addAction(self.actionViews2DEditor)
        self.menuViews.addSeparator()
        self.menuViews.addAction(self.menuViews2DPlot.menuAction())
        self.menuViews.addAction(self.menuViews3DPlot.menuAction())
        self.menuViews.addSeparator()
        self.menuViews.addAction(self.actionViewsLog)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuContext.menuAction())
        self.menuBar.addAction(self.menuSampleElement.menuAction())
        self.menuBar.addAction(self.menuSystem.menuAction())
        self.menuBar.addAction(self.menuSimulator.menuAction())
        self.menuBar.addAction(self.menu2DEditor.menuAction())
        self.menuBar.addAction(self.menu3DView.menuAction())
        self.menuBar.addAction(self.menuViews.menuAction())
        self.menuBar.addAction(self.menuConfiguration.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.comboBoxLogLevel.setCurrentIndex(2)
        QtCore.QObject.connect(self.action2DEditorXYZ, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.action2DEditorXY.setDisabled)
        QtCore.QObject.connect(self.action2DEditorXYZ, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.action2DEditorXZ.setDisabled)
        QtCore.QObject.connect(self.action2DEditorXYZ, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.action2DEditorYZ.setDisabled)
        QtCore.QObject.connect(self.horizontalSlider2DEditorZIndex, QtCore.SIGNAL(_fromUtf8("sliderMoved(int)")), self.spinBox2DEditorZIndex.setValue)
        QtCore.QObject.connect(self.horizontalSlider2DEditorXIndex, QtCore.SIGNAL(_fromUtf8("sliderMoved(int)")), self.spinBox2DEditorXIndex.setValue)
        QtCore.QObject.connect(self.horizontalSlider2DEditorYIndex, QtCore.SIGNAL(_fromUtf8("sliderMoved(int)")), self.spinBox2DEditorYIndex.setValue)
        QtCore.QObject.connect(self.spinBox2DEditorZIndex, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.horizontalSlider2DEditorZIndex.setValue)
        QtCore.QObject.connect(self.spinBox2DEditorXIndex, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.horizontalSlider2DEditorXIndex.setValue)
        QtCore.QObject.connect(self.spinBox2DEditorYIndex, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.horizontalSlider2DEditorYIndex.setValue)
        QtCore.QObject.connect(self.action3DView, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.action3DViewCameraXYZ.setEnabled)
        QtCore.QObject.connect(self.action3DView, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.action3DViewCameraXY.setEnabled)
        QtCore.QObject.connect(self.action3DView, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.action3DViewCameraXZ.setEnabled)
        QtCore.QObject.connect(self.action3DView, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.action3DViewCameraYZ.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MRSPRINT", None))
        self.toolBarSampleElement.setWindowTitle(_translate("MainWindow", "Tool Bar Sample Element", None))
        self.toolBarSampleElement.setToolTip(_translate("MainWindow", "Sample related actions", None))
        self.toolBar2DEditor.setWindowTitle(_translate("MainWindow", "Tool Bar 2D Editor", None))
        self.toolBar2DEditor.setToolTip(_translate("MainWindow", "2D editor related actions", None))
        self.toolBar3DViewCamera.setWindowTitle(_translate("MainWindow", "Tool Bar 3D View Camera", None))
        self.toolBar3DViewCamera.setToolTip(_translate("MainWindow", " 3D view camera related actions", None))
        self.dockWidgetParameters.setWindowTitle(_translate("MainWindow", "Parameters", None))
        self.dockWidget2DEditorXY.setWindowTitle(_translate("MainWindow", "Axial - Plane XY", None))
        self.label2DEditorZIndex.setText(_translate("MainWindow", "Z Index", None))
        self.dockWidget2DEditorYZ.setWindowTitle(_translate("MainWindow", "Sagittal - Plane YZ", None))
        self.label2DEditorXIndex.setText(_translate("MainWindow", "X Index", None))
        self.dockWidget2DEditorXZ.setWindowTitle(_translate("MainWindow", "Coronal - Plane XZ", None))
        self.label2DEditorYIndex.setText(_translate("MainWindow", "Y Index", None))
        self.toolBarContext.setWindowTitle(_translate("MainWindow", "Tool Bar Context", None))
        self.toolBarContext.setToolTip(_translate("MainWindow", "Main window context/perspective", None))
        self.toolBar3DView.setWindowTitle(_translate("MainWindow", "Tool Bar 3D View", None))
        self.toolBar3DView.setToolTip(_translate("MainWindow", "3D view related actions", None))
        self.toolBarFile.setWindowTitle(_translate("MainWindow", "Tool Bar File", None))
        self.toolBarFile.setToolTip(_translate("MainWindow", "File related actions", None))
        self.toolBarFieldInhomogeneity.setWindowTitle(_translate("MainWindow", "Tool Bar Field Inhomogeneity", None))
        self.toolBarFieldInhomogeneity.setToolTip(_translate("MainWindow", "System related actions, field inhomogeneity", None))
        self.toolBarSimulator.setWindowTitle(_translate("MainWindow", "Tool Bar Simulator", None))
        self.dockWidgetExplorer.setToolTip(_translate("MainWindow", "Find files to be load.", None))
        self.dockWidgetExplorer.setWindowTitle(_translate("MainWindow", "Explorer", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuSampleElement.setTitle(_translate("MainWindow", "Sample", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.menuConfiguration.setTitle(_translate("MainWindow", "Settings", None))
        self.menu2DEditor.setTitle(_translate("MainWindow", "2D Editor", None))
        self.menu3DView.setTitle(_translate("MainWindow", "3D View", None))
        self.menuContext.setTitle(_translate("MainWindow", "Context", None))
        self.menuSystem.setTitle(_translate("MainWindow", "System", None))
        self.menuSimulator.setTitle(_translate("MainWindow", "Simulator", None))
        self.menuViews.setTitle(_translate("MainWindow", "Views", None))
        self.menuViews3DPlot.setTitle(_translate("MainWindow", "3D Plot", None))
        self.menuViews2DPlot.setTitle(_translate("MainWindow", "2D Plot", None))
        self.dockWidgetLog.setWindowTitle(_translate("MainWindow", "Log", None))
        self.comboBoxLogLevel.setItemText(0, _translate("MainWindow", "ERROR", None))
        self.comboBoxLogLevel.setItemText(1, _translate("MainWindow", "WARNING", None))
        self.comboBoxLogLevel.setItemText(2, _translate("MainWindow", "INFO", None))
        self.comboBoxLogLevel.setItemText(3, _translate("MainWindow", "DEBUG", None))
        self.pushButtonLogReset.setToolTip(_translate("MainWindow", "Clean log", None))
        self.actionSampleElementT1.setText(_translate("MainWindow", "T1", None))
        self.actionSampleElementT1.setToolTip(_translate("MainWindow", "T1 - Longitudinal magnetization", None))
        self.actionSampleElementT2.setText(_translate("MainWindow", "T2", None))
        self.actionSampleElementT2.setToolTip(_translate("MainWindow", "T2 - Transerse magnetization", None))
        self.actionSampleElementRho.setText(_translate("MainWindow", "ρ", None))
        self.actionSampleElementRho.setToolTip(_translate("MainWindow", "ρ - Density of spins", None))
        self.action2DEditorXY.setText(_translate("MainWindow", "Axial (XY)", None))
        self.action2DEditorXZ.setText(_translate("MainWindow", "Coronal (XZ)", None))
        self.action2DEditorYZ.setText(_translate("MainWindow", "Sagittal (YZ)", None))
        self.action3DViewColor.setText(_translate("MainWindow", "Color", None))
        self.action3DViewColor.setToolTip(_translate("MainWindow", "Represents parameters on colors", None))
        self.actionFileNew.setText(_translate("MainWindow", "New", None))
        self.actionFileOpen.setText(_translate("MainWindow", "Open ...", None))
        self.actionFileSave.setText(_translate("MainWindow", "Save", None))
        self.actionFileSaveAs.setText(_translate("MainWindow", "Save As ...", None))
        self.actionFileClose.setText(_translate("MainWindow", "Close", None))
        self.actionQuit.setText(_translate("MainWindow", "Quit", None))
        self.actionFileExamples.setText(_translate("MainWindow", "Examples", None))
        self.action2DEditorXYZ.setText(_translate("MainWindow", "All", None))
        self.action2DEditorXYZ.setToolTip(_translate("MainWindow", "All 2D editors are opened/closed", None))
        self.actionConfigurationPreferences.setText(_translate("MainWindow", "Preferences ...", None))
        self.action3DView.setText(_translate("MainWindow", "3D View", None))
        self.action3DView.setToolTip(_translate("MainWindow", "Enable/Disable 3D View", None))
        self.action2DEditorGradient.setText(_translate("MainWindow", "Gradient", None))
        self.action2DEditorGradient.setToolTip(_translate("MainWindow", "Creates a gradient over values", None))
        self.action3DViewCameraXYZ.setText(_translate("MainWindow", "Camera Diagonal (XYZ)", None))
        self.action3DViewCameraXYZ.setToolTip(_translate("MainWindow", "Diagonal View", None))
        self.action3DViewCameraXY.setText(_translate("MainWindow", "Camera Axial (XY)", None))
        self.action3DViewCameraXY.setToolTip(_translate("MainWindow", "Axial View - XY", None))
        self.action3DViewCameraXZ.setText(_translate("MainWindow", "Camera Coronal (XZ)", None))
        self.action3DViewCameraXZ.setToolTip(_translate("MainWindow", "Coronal View - XZ", None))
        self.action3DViewCameraYZ.setText(_translate("MainWindow", "Camera Sagittal (YZ)", None))
        self.action3DViewCameraYZ.setToolTip(_translate("MainWindow", "Sagittal View - YZ", None))
        self.actionContextSample.setText(_translate("MainWindow", "Sample", None))
        self.actionContextSample.setToolTip(_translate("MainWindow", "Sample editor context", None))
        self.actionContextSystem.setText(_translate("MainWindow", "System", None))
        self.actionContextSystem.setToolTip(_translate("MainWindow", "System editor context", None))
        self.actionContextSequence.setText(_translate("MainWindow", "Sequence", None))
        self.actionContextSequence.setToolTip(_translate("MainWindow", "Sequence editor context", None))
        self.actionContextProcessing.setText(_translate("MainWindow", "Processing", None))
        self.actionContextProcessing.setToolTip(_translate("MainWindow", "Processing editor context", None))
        self.action2DEditorColor.setText(_translate("MainWindow", "Color", None))
        self.action2DEditorColor.setToolTip(_translate("MainWindow", "Enable/disable colors over 2D editor", None))
        self.actionSampleElementAll.setText(_translate("MainWindow", "All", None))
        self.actionSampleElementAll.setToolTip(_translate("MainWindow", "Show all element sample paremeters", None))
        self.action2DEditor.setText(_translate("MainWindow", "2D Editor", None))
        self.action2DEditor.setToolTip(_translate("MainWindow", "Show 2D editor", None))
        self.action3DViewXGrid.setText(_translate("MainWindow", "X Grid", None))
        self.action3DViewYGrid.setText(_translate("MainWindow", "Y Grid", None))
        self.action3DViewZGrid.setText(_translate("MainWindow", "Z Grid", None))
        self.action3DViewXYZAxis.setText(_translate("MainWindow", "XYZ Axis", None))
        self.action3DViewInvertBackground.setText(_translate("MainWindow", "Invert 3D Background", None))
        self.action3DViewInvertBackground.setToolTip(_translate("MainWindow", "Invert 3D Background", None))
        self.action2DEditorInvertBackground.setText(_translate("MainWindow", "Invert 2D Background", None))
        self.actionContextSimulator.setText(_translate("MainWindow", "Simulator", None))
        self.actionContextSimulator.setToolTip(_translate("MainWindow", "Simulator editor context", None))
        self.actionFieldInhomogeneityB0X.setText(_translate("MainWindow", "Field Inhomogeneity B0X", None))
        self.actionFieldInhomogeneityB0X.setToolTip(_translate("MainWindow", "Field Inhomogeneity B0X", None))
        self.actionFieldInhomogeneityB0Y.setText(_translate("MainWindow", "Field Inhomogeneity B0Y", None))
        self.actionFieldInhomogeneityB0Y.setToolTip(_translate("MainWindow", "Field Inhomogeneity B0Y", None))
        self.actionFieldInhomogeneityB0Z.setText(_translate("MainWindow", "Field Inhomogeneity B0Z", None))
        self.actionFieldInhomogeneityB0Z.setToolTip(_translate("MainWindow", "Field Inhomogeneity B0Z", None))
        self.actionFieldInhomogeneityAll.setText(_translate("MainWindow", "All", None))
        self.actionFieldInhomogeneityAll.setToolTip(_translate("MainWindow", "Field inhomogeneity resultant component", None))
        self.actionSimulatorPlay.setText(_translate("MainWindow", "Play", None))
        self.actionSimulatorPlay.setToolTip(_translate("MainWindow", "Play a simulated data", None))
        self.actionSimulatorStop.setText(_translate("MainWindow", "Stop", None))
        self.actionSimulatorStop.setToolTip(_translate("MainWindow", "Stop playing or calculating", None))
        self.actionSimulatorPause.setText(_translate("MainWindow", "Pause", None))
        self.actionSimulatorPause.setToolTip(_translate("MainWindow", "Pause a play", None))
        self.actionSimulatorCalculate.setText(_translate("MainWindow", "Calculate", None))
        self.actionSimulatorCalculate.setToolTip(_translate("MainWindow", "Calculate simulation data (do not play)", None))
        self.actionContextProtocol.setText(_translate("MainWindow", "Protocol", None))
        self.actionContextProtocol.setToolTip(_translate("MainWindow", "Procotol context", None))
        self.actionSampleElementNucleus.setText(_translate("MainWindow", "Nucleus", None))
        self.actionSampleElementNucleus.setToolTip(_translate("MainWindow", "Nucleus", None))
        self.actionAbout.setText(_translate("MainWindow", "About", None))
        self.actionViewsParameters.setText(_translate("MainWindow", "Parameters", None))
        self.actionViewsParameters.setToolTip(_translate("MainWindow", "Parameters View", None))
        self.actionViewsExplorer.setText(_translate("MainWindow", "Explorer", None))
        self.actionViewsExplorer.setToolTip(_translate("MainWindow", "Explorer View", None))
        self.actionViews2DEditor.setText(_translate("MainWindow", "2D Editor", None))
        self.actionViews2DEditor.setToolTip(_translate("MainWindow", "2D Editor", None))
        self.actionViews2DProcessing.setText(_translate("MainWindow", "Processing", None))
        self.actionViews2DProcessing.setToolTip(_translate("MainWindow", "View processing 2D", None))
        self.actionViews2DMagnetization.setText(_translate("MainWindow", "Magnetization", None))
        self.actionViews2DMagnetization.setToolTip(_translate("MainWindow", "View magnetization 2D", None))
        self.actionViewsLog.setText(_translate("MainWindow", "Log", None))
        self.actionViewsLog.setToolTip(_translate("MainWindow", "Log View", None))
        self.actionViews3DSample.setText(_translate("MainWindow", "Sample", None))
        self.actionViews3DSample.setToolTip(_translate("MainWindow", "View sample 3D", None))
        self.actionViews3DSystem.setText(_translate("MainWindow", "System", None))
        self.actionViews3DSystem.setToolTip(_translate("MainWindow", "View system 3D", None))
        self.actionViews2DKSpace.setText(_translate("MainWindow", "K-Space", None))
        self.actionViews2DKSpace.setToolTip(_translate("MainWindow", "View k-space 2D", None))
        self.actionViews3DSimulator.setText(_translate("MainWindow", "Simulator", None))
        self.actionViews3DSimulator.setToolTip(_translate("MainWindow", "View simulator 3D", None))

from mrsprint.gui import mrsprint_rc
