
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-07-12T09:52:06-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "65e48d8acd94be7de433866726bf2d93c1d80f28",
 "version": "0.41.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
