__title__ = 'guide-gitlab'
__description__ = 'Limited Python wrapper for the Gitlab API'
__url__ = 'https://github.com/JohnPickerill/'
__version_info__ = ('0', '0', '21')
__version__ = '.'.join(__version_info__)
__author__ = 'John Pickerill'
__author_email__ = 'john.pickerill@landregistry.gov.uk'
__maintainer__ = 'Land Registry'
__license__ = 'MIT'
__copyright__ = '(c) 2017 by John Pickerill'
